# Compare each executable's compiled citations with the canonical registry.
cmake_minimum_required(VERSION 3.24)
file(READ "${CMAKE_CURRENT_LIST_DIR}/../data/citations.json" registry)
string(JSON tool_count LENGTH "${registry}" tools)
math(EXPR last_tool "${tool_count} - 1")
set(selected_ids)
foreach(index RANGE ${last_tool})
  string(JSON name GET "${registry}" tools ${index} executable)
  if(name STREQUAL TOOL)
    string(JSON uses GET "${registry}" tools ${index} references)
    string(JSON use_count LENGTH "${uses}")
    math(EXPR last_use "${use_count} - 1")
    foreach(use RANGE ${last_use})
      string(JSON id GET "${uses}" ${use} id)
      list(APPEND selected_ids "${id}")
    endforeach()
    break()
  endif()
endforeach()
if(NOT selected_ids)
  message(FATAL_ERROR "No citation mapping for ${TOOL}")
endif()

execute_process(COMMAND "${PROGRAM}" --help
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
if(NOT status EQUAL 0 OR NOT error STREQUAL "" OR NOT output MATCHES "\nReferences:\n")
  message(FATAL_ERROR "Missing citation help for ${TOOL}: ${status}\n${output}\n${error}")
endif()
set(help "${output}")
function(contains needle)
  string(FIND "${help}" "${needle}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "${TOOL} help is missing '${needle}'\n${help}")
  endif()
endfunction()
string(JSON ref_count LENGTH "${registry}" references)
math(EXPR last_ref "${ref_count} - 1")
foreach(index RANGE ${last_ref})
  string(JSON ref GET "${registry}" references ${index})
  string(JSON id GET "${ref}" id)
  string(REGEX MATCHALL "\\[${id}\\]" matches "${help}")
  list(LENGTH matches count)
  if(id IN_LIST selected_ids)
    if(NOT count EQUAL 1)
      message(FATAL_ERROR "${TOOL} needs exactly one [${id}], got ${count}")
    endif()
    foreach(field IN ITEMS authors title publication)
      string(JSON value GET "${ref}" ${field})
      contains("${value}")
    endforeach()
    string(JSON year GET "${ref}" year)
    if(year)
      contains("(${year})")
    endif()
    string(JSON link_count LENGTH "${ref}" links)
    math(EXPR last_link "${link_count} - 1")
    foreach(link RANGE ${last_link})
      string(JSON url GET "${ref}" links ${link} url)
      contains("${url}")
    endforeach()
  elseif(NOT count EQUAL 0)
    message(FATAL_ERROR "Unrelated citation [${id}] appears in ${TOOL} help")
  endif()
endforeach()
foreach(use RANGE ${last_use})
  string(JSON context GET "${uses}" ${use} context)
  contains("Used for: ${context}")
endforeach()

# No-argument usage retains its stderr/exit-1 contract and the same citations.
execute_process(COMMAND "${PROGRAM}"
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
if(NOT status EQUAL 1 OR NOT output STREQUAL "" OR NOT error STREQUAL help)
  message(FATAL_ERROR "No-argument usage differs from --help for ${TOOL}\n${output}\n${error}")
endif()

set(args 4)
if(TOOL MATCHES "xxz")
  list(APPEND args --delta 0.5)
elseif(TOOL MATCHES "hubbard")
  list(APPEND args --u 4)
elseif(TOOL MATCHES "lieb-liniger")
  list(APPEND args --length 4 --c 1)
elseif(TOOL MATCHES "su3")
  set(args 6)
elseif(TOOL MATCHES "gaudin-yang")
  set(args 6 --length 6 --c 1)
elseif(TOOL STREQUAL "bethe-richardson")
  set(args --levels 0,1,2,3 --pairs 2 --g 1)
elseif(TOOL STREQUAL "bethe-central-spin")
  set(args --couplings 1,0.7,0.3 --field 1 --sz 0)
endif()
execute_process(COMMAND "${PROGRAM}" ${args}
  RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
if(NOT status EQUAL 0 OR "${output}${error}" MATCHES "References:|CITATIONS.md")
  message(FATAL_ERROR "Calculation output gained unwanted citation text for ${TOOL}\n${output}\n${error}")
endif()
