include("${CMAKE_CURRENT_LIST_DIR}/check_cpu_time.cmake")
set(ENV{UNI20_COLOR} never)
set(ENV{UNI20_GLYPHS} ascii)
set(ENV{COLUMNS} 200)
function(check_cli expected_status expected_text)
  execute_process(COMMAND "${PROGRAM}" ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
  if(NOT "${status}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "Unexpected status ${status} for ${ARGN}\n${output}\n${error}")
  endif()
  string(FIND "${output}${error}" "${expected_text}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${expected_text}' for ${ARGN}\n${output}\n${error}")
  endif()
  if((expected_status EQUAL 0 OR expected_status EQUAL 2) AND NOT output MATCHES "^Usage:")
    normalize_cpu_time(output output)
  endif()
  set(output "${output}" PARENT_SCOPE)
endfunction()
check_cli(0 "Usage: bethe-tj-pbc" --help)
check_cli(0 "Calculation: no-hole XXX reduction" 4)
set(default_output "${output}")
check_cli(0 "Precision: fp64" 4 --precision fp64 --format plain)
if(NOT output STREQUAL default_output)
  message(FATAL_ERROR "Defaults differ from explicit fp64/plain")
endif()
check_cli(0 "First-level roots: 5" 8 --particles 6 --roots)
foreach(field IN ITEMS "Second-level roots: 2" "Holes: 2" "Momentum index: 0" "First-level rapidities" "Second-level rapidities")
  string(FIND "${output}" "${field}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing t-J field ${field}\n${output}")
  endif()
endforeach()
check_cli(0 "Occupied free modes" 7 --particles 4 --sz 2 --roots --max-iterations 0)
check_cli(0 "Total energy: 0" 7 --particles 0)
check_cli(0 "N_down: 3" 8 --particles 4 --sz -1)
check_cli(2 "iteration limit reached" 8 --particles 6 --max-iterations 0)
check_cli(1 "odd N_up AND odd N_down" 8 --particles 4)
check_cli(1 "odd N_up AND odd N_down" 8 --particles 5)
check_cli(1 "particles <= L" 8 --particles 9)
check_cli(1 "same parity as N" 8 --particles 6 --sz 1/2)
check_cli(1 "3 <= L" 2)
check_cli(1 "unknown option" 8 --j 2)
check_cli(1 "unknown option" 8 --excitations all)
check_cli(1 "missing value" 8 --particles)
check_cli(1 "unknown output format" 8 --format json)
check_cli(1 "unknown precision" 8 --precision fp16)
foreach(tol IN ITEMS 0 -1 nan inf)
  check_cli(1 "tolerance must be finite and positive" 8 --particles 6 --tolerance ${tol})
endforeach()
set(precisions fp64 long-double)
if(FLOAT128)
  list(APPEND precisions fp128)
else()
  check_cli(1 "fp128 is unavailable" 8 --precision fp128)
endif()
foreach(precision IN LISTS precisions)
  check_cli(0 "Total energy: -5.236067977499" 5 --particles 4 --sz 1 --precision ${precision})
  string(REGEX MATCH "Total energy: ([^\n]+)" match "${output}")
  set(energy "${CMAKE_MATCH_1}")
  set(ENV{COLUMNS} 20)
  check_cli(0 "${energy}" 5 --particles 4 --sz 1 --precision ${precision} --roots --format pretty)
  set(ENV{COLUMNS} 200)
  check_cli(0 "Status: converged" 96 --particles 48 --sz 1 --precision ${precision})
endforeach()
if(FLOAT128)
  check_cli(0 "Total energy: -5.23606797749978969640917366" 5 --particles 4 --sz 1 --precision fp128)
  check_cli(0 "Residual tolerance: 1.1234567890123456789012345678" 8 --particles 6 --precision fp128 --tolerance 1.12345678901234567890123456789e-30)
endif()
