include("${CMAKE_CURRENT_LIST_DIR}/check_cpu_time.cmake")
set(ENV{UNI20_COLOR} never)
set(ENV{UNI20_GLYPHS} ascii)
set(ENV{UNI20_CHARSET} escape)
set(ENV{COLUMNS} 200)
unset(ENV{NO_COLOR})
string(ASCII 27 escape)

function(check_cli expected_status expected_text)
  execute_process(COMMAND "${PROGRAM}" ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
  if(NOT "${status}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "Unexpected status ${status} for ${ARGN}\n${output}\n${error}")
  endif()
  string(FIND "${output}${error}" "${expected_text}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${expected_text}' for ${ARGN}\n${output}\n${error}")
  endif()
  if((expected_status EQUAL 0 OR expected_status EQUAL 2) AND NOT output MATCHES "^Usage:")
    normalize_cpu_time(output output)
    if(output MATCHES "Heisenberg|Multiplet|multiplets|scaled rapidity")
      message(FATAL_ERROR "Hubbard report contains spin-chain metadata\n${output}")
    endif()
  endif()
  set(output "${output}" PARENT_SCOPE)
endfunction()

check_cli(0 "Usage: bethe-hubbard-pbc" --help)
check_cli(0 "Total energy: -2.102748483462" 4 --u 4)
set(default_output "${output}")
check_cli(0 "Precision: fp64" 4 --u 4 --particles 4 --sz 0 --precision fp64 --format plain)
if(NOT output STREQUAL default_output)
  message(FATAL_ERROR "Hubbard defaults differ from explicit fp64/plain/half filling/Sz=0")
endif()
check_cli(0 "Momentum index: 2" 4 --u 4 --roots)
check_cli(0 "Momentum index: 0" 6 --u 4 --roots)
check_cli(0 "# index Lambda J" 6 --u 4 --roots)
check_cli(0 "# index k I" 6 --u 4 --roots)
check_cli(0 "Completed continuation stages: 4" 6 --u 1)
check_cli(0 "Total energy: -8" 6 --u 0 --max-iterations 0 --roots)
if(output MATCHES "# index Lambda J|# index k I")
  message(FATAL_ERROR "U=0 free occupations have spurious Bethe labels")
endif()
check_cli(0 "free-fermion occupations; no Bethe labels" 6 --u 0 --roots)
check_cli(0 "Iterations: 0" 4 --u 0 --max-iterations 0)
check_cli(2 "iteration limit reached; unconverged estimate" 6 --u 0.01 --max-iterations 0)
check_cli(2 "Iterations: 1" 6 --u 0.01 --max-iterations 1)
check_cli(2 "iteration limit reached; unconverged estimate" 6 --u 0.01 --max-iterations 5 --format pretty)
check_cli(2 "line search stalled; unconverged estimate" 8 --u 1e-30 --precision fp64)
check_cli(0 "Hubbard (periodic) - half-filled ground state" 6 --u 4 --format pretty)
check_cli(0 "Spin rapidities (conventional Lambda)" 6 --u 4 --roots --format pretty)
check_cli(0 "Free-fermion occupied momenta (no Bethe labels)" 6 --u 0 --roots --format pretty)

check_cli(1 "Usage:")
check_cli(1 "--u VALUE is required" 4)
foreach(option IN ITEMS --u --particles --sz --precision --tolerance --max-iterations --format)
  check_cli(1 "missing value" 4 ${option})
endforeach()
foreach(u IN ITEMS -1 nan inf -inf)
  check_cli(1 "finite U >= 0" 4 --u ${u})
endforeach()
check_cli(1 "invalid real value" 4 --u 4junk)
check_cli(1 "out of range" 4 --u 1e-310)
foreach(n IN ITEMS 0 1 3 5)
  check_cli(1 "requires even" ${n} --u 4)
endforeach()
check_cli(1 "invalid nonnegative integer" -1 --u 4)
check_cli(1 "invalid nonnegative integer" 4 --u 4 --max-iterations -1)
check_cli(1 "only half filling" 4 --u 4 --particles 2)
check_cli(1 "only Sz=0" 4 --u 4 --sz 1)
check_cli(1 "only Sz=0" 4 --u 4 --sz -1/2)
check_cli(1 "parse failed" 4 --u 4 --sz 0.25)
foreach(option IN ITEMS --excitations --quantum-numbers --sectors --spin --boundary)
  check_cli(1 "unknown option: ${option}" 4 --u 4 ${option} 1)
endforeach()
check_cli(1 "unknown precision" 4 --u 4 --precision arbitrary)
check_cli(1 "unknown output format" 4 --u 4 --format arbitrary)
foreach(tol IN ITEMS 0 -1 nan inf)
  check_cli(1 "finite and positive" 4 --u 4 --tolerance ${tol})
endforeach()

set(precisions fp64 long-double)
if(FLOAT128)
  list(APPEND precisions fp128)
  check_cli(0 "Total energy: -2.47213595499957939281834733746" 2 --u 4 --precision fp128)
  check_cli(0 "U: 4.1234567890123456789012345678" 4 --u 4.12345678901234567890123456789 --precision fp128)
else()
  check_cli(1 "fp128 is unavailable" 4 --u 4 --precision fp128)
endif()
foreach(precision IN LISTS precisions)
  foreach(u IN ITEMS 0 4)
    check_cli(0 "Total energy:" 6 --u ${u} --roots --precision ${precision} --format plain)
    set(plain "${output}")
    # Pretty labels are exact fractions, plain labels are decimals. Compare all
    # floating fields and root values after removing the small half-integer labels.
    string(REGEX REPLACE " -?[0-9]+\\.5\n" "\n" values "${output}")
    string(REGEX MATCHALL "-?[0-9]+\\.[0-9]+([eE][+-]?[0-9]+)?" tokens "${values}")
    foreach(width IN ITEMS 200 35)
      set(ENV{COLUMNS} ${width})
      check_cli(0 "Hubbard (periodic)" 6 --u ${u} --roots --precision ${precision} --format pretty)
      foreach(token IN LISTS tokens)
        string(FIND "${output}" "${token}" match)
        if(match EQUAL -1)
          message(FATAL_ERROR "Lost numeric token '${token}' for ${precision}\n${output}")
        endif()
      endforeach()
    endforeach()
    set(ENV{UNI20_COLOR} always)
    check_cli(0 "Total energy:" 6 --u ${u} --roots --precision ${precision})
    if(NOT output STREQUAL plain)
      message(FATAL_ERROR "Hubbard piped auto output differs from plain")
    endif()
    check_cli(0 "${escape}[" 6 --u ${u} --roots --precision ${precision} --format pretty)
    set(ENV{UNI20_COLOR} never)
  endforeach()
endforeach()
set(ENV{UNI20_COLOR} auto)
set(ENV{NO_COLOR} 1)
check_cli(0 "Hubbard" 4 --u 4 --format pretty)
if(output MATCHES "${escape}")
  message(FATAL_ERROR "NO_COLOR left ANSI sequences")
endif()
