include("${CMAKE_CURRENT_LIST_DIR}/check_cpu_time.cmake")
set(ENV{UNI20_COLOR} never)
set(ENV{UNI20_GLYPHS} ascii)
set(ENV{COLUMNS} 200)

function(check_cli expected_status expected_text)
  execute_process(COMMAND "${PROGRAM}" ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
  if(NOT "${status}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "Unexpected status ${status} for ${ARGN}\n${output}\n${error}")
  endif()
  string(FIND "${output}${error}" "${expected_text}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${expected_text}' for ${ARGN}\n${output}\n${error}")
  endif()
  if((expected_status EQUAL 0 OR expected_status EQUAL 2) AND NOT "--help" IN_LIST ARGN)
    normalize_cpu_time(output output)
  endif()
  set(output "${output}" PARENT_SCOPE)
endfunction()

check_cli(0 "bethe-biquadratic-obc" --help)
check_cli(0 "Status: converged" 4)
set(default_output "${output}")
check_cli(0 "Precision: fp64" 4 --precision fp64 --format plain)
if(NOT output STREQUAL default_output)
  message(FATAL_ERROR "Defaults differ from explicit fp64/plain")
endif()
check_cli(0 "Reference XXZ roots" 6 --roots)
foreach(field IN ITEMS "Spin: 1" "Total spin: 0" "TL loop weight: 3" "TL through-lines: 0"
    "Ground-state multiplicity: 1" "XXZ Delta: 1.5" "XXZ reference energy:" "Residual norm:" "alpha")
  string(FIND "${output}" "${field}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${field}'\n${output}")
  endif()
endforeach()
if(output MATCHES "Momentum")
  message(FATAL_ERROR "Open chain acquired a momentum label")
endif()
check_cli(2 "iteration limit reached; unconverged estimate" 8 --max-iterations 0 --roots)
check_cli(2 "Iterations: 1" 8 --max-iterations 1)
check_cli(2 "unconverged estimate" 8 --tolerance 1e-30)
check_cli(2 "unconverged estimate" 8 --max-iterations 0 --format pretty)
check_cli(1 "2 <= sites" 0)
check_cli(1 "2 <= sites" 1)
foreach(bad IN ITEMS 3 5 7)
  check_cli(1 "requires even sites" ${bad})
endforeach()
foreach(bad IN ITEMS -4 4.5 4junk)
  check_cli(1 "nonnegative" ${bad})
endforeach()
foreach(option IN ITEMS --precision --format --tolerance --max-iterations --through-lines --excitations --max-candidates --quantum-numbers)
  check_cli(1 "missing" 4 ${option})
endforeach()
foreach(bad IN ITEMS 0 -1 nan inf -inf)
  check_cli(1 "residual tolerance must be finite and positive" 4 --tolerance ${bad})
endforeach()
check_cli(1 "Newton matrix is too large" 1000000000000000000)
check_cli(1 "not in {fp64,long-double,fp128}" 4 --precision fp16)
check_cli(1 "not in {auto,pretty,plain,csv,tsv,json}" 4 --format invalid)
check_cli(1 "invalid real value" 4 --tolerance 1junk)
check_cli(1 "nonnegative" 4 --max-iterations -1)
foreach(option IN ITEMS --spin --sz --delta --j --bogus)
  check_cli(1 "not expected" 4 ${option})
endforeach()
check_cli(0 "Candidates: 10" 8 --excitations all)
set(all_output "${output}")
check_cli(0 "Returned levels: 10" 8 --excitations 100 --through-lines 2)
if(NOT output STREQUAL all_output)
  message(FATAL_ERROR "all differs from a sufficient count or default ELL=2")
endif()
check_cli(0 "Returned levels: 2" 8 --excitations 2)
foreach(field IN ITEMS "Candidates: 10" "Converged candidates: 10" "Multiplicity per TL eigenvector: 8"
    "NOT the complete TL spectrum" "E-E0; global singlet ground state")
  string(FIND "${output}" "${field}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Excitation report missing '${field}'\n${output}")
  endif()
endforeach()
if(output MATCHES "Total spin:|Momentum")
  message(FATAL_ERROR "TL excitation was given a physical-spin or momentum label")
endif()
check_cli(0 "Returned levels: 1" 8 --through-lines 0 --excitations all)
check_cli(0 "Multiplicity per TL eigenvector: 8" 4 --through-lines 2)
check_cli(0 "Total energy: -6" 4 --quantum-numbers 2)
check_cli(0 "Multiplicity per TL eigenvector: 55" 4 --quantum-numbers none)
check_cli(0 "overflow (>uint64)" 46 --through-lines 46)
check_cli(0 "TL module minima (not physical-spin sectors)" 4 --sectors --roots)
check_cli(2 "failed candidates excluded" 8 --excitations all --max-iterations 0)
check_cli(2 "First failed I:" 8 --excitations all --max-iterations 0 --roots)
check_cli(2 "Returned levels: 1" 8 --through-lines 8 --excitations all --max-iterations 0)
check_cli(2 "unavailable; ground solve failed" 8 --through-lines 8 --excitations all --max-iterations 0)
check_cli(2 "incomplete; unconverged estimates" 8 --sectors --max-iterations 0)
check_cli(1 "exceeds max_candidates" 8 --excitations 1 --max-candidates 9)
check_cli(1 "exceeds max_candidates" 1000000000000000000 --excitations all)
foreach(bad IN ITEMS 1 3 10)
  check_cli(1 "TL through-lines must be even" 8 --through-lines ${bad})
endforeach()
foreach(bad IN ITEMS 0 1/2 1,1 2,1 4 1,4 1,2,3)
  check_cli(1 "quantum-group XXZ" 4 --quantum-numbers ${bad})
endforeach()
check_cli(1 "must be positive" 8 --excitations 0)
check_cli(1 "must be positive" 8 --excitations all --max-candidates 0)
check_cli(1 "--max-candidates requires" 8 --max-candidates 20)
check_cli(1 "cannot be combined" 8 --sectors --through-lines 2)
check_cli(1 "cannot be combined" 8 --sectors --excitations all)
check_cli(1 "cannot be combined" 8 --sectors --quantum-numbers 1,2,3)
check_cli(1 "cannot combine" 8 --quantum-numbers 1,2,3 --through-lines 2)
check_cli(1 "cannot combine" 8 --quantum-numbers 1,2,3 --excitations all)
set(precisions fp64 long-double)
if(FLOAT128)
  list(APPEND precisions fp128)
else()
  check_cli(1 "fp128 is unavailable" 4 --precision fp128)
endif()
foreach(precision IN LISTS precisions)
  check_cli(0 "Total energy: -4" 2 --precision ${precision})
  check_cli(0 "Total energy: -9.561552812808" 4 --precision ${precision} --roots)
  string(REGEX MATCH "Total energy: ([^\n]+)" match "${output}")
  set(energy "${CMAKE_MATCH_1}")
  set(ENV{COLUMNS} 20)
  check_cli(0 "${energy}" 4 --precision ${precision} --roots --format pretty)
  set(ENV{COLUMNS} 200)
  check_cli(0 "Status: converged" 128 --precision ${precision})
  check_cli(0 "-7.41421356237309" 4 --excitations all --roots --precision ${precision})
  set(ENV{COLUMNS} 20)
  check_cli(0 "-7.41421356237309" 4 --excitations all --roots --precision ${precision} --format pretty)
  check_cli(0 "Multiplicity" 4 --sectors --precision ${precision} --format pretty)
  set(ENV{COLUMNS} 200)
  check_cli(0 "Status: converged" 16 --excitations 4 --precision ${precision})
  check_cli(0 "Status: converged" 16 --sectors --precision ${precision})
endforeach()
if(FLOAT128)
  check_cli(0 "Residual tolerance: 1.1234567890123456789012345678" 4 --precision fp128 --tolerance 1.12345678901234567890123456789e-30)
  check_cli(0 "Total energy: -9.561552812808830274910704927" 4 --precision fp128)
  check_cli(0 "-7.414213562373095048801688724" 4 --excitations all --precision fp128)
  check_cli(0 "2.147339250435735226109016203" 4 --excitations all --precision fp128)
endif()
