# Shared checks for the separate periodic and free-end front ends.
include("${CMAKE_CURRENT_LIST_DIR}/check_cpu_time.cmake")
set(ENV{UNI20_COLOR} never)
set(ENV{UNI20_GLYPHS} ascii)
set(ENV{UNI20_CHARSET} escape)
set(ENV{COLUMNS} 200)
unset(ENV{NO_COLOR})
string(ASCII 27 escape)

function(check_cli expected_status expected_text)
  execute_process(COMMAND "${PROGRAM}" ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
  if(NOT "${status}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "Unexpected status ${status} for ${ARGN}\n${output}\n${error}")
  endif()
  string(FIND "${output}${error}" "${expected_text}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${expected_text}' for ${ARGN}\n${output}\n${error}")
  endif()
  if(expected_status EQUAL 0 OR expected_status EQUAL 2)
    normalize_cpu_time(output output)
    if(PROGRAM MATCHES "bethe-xxx-obc" AND output MATCHES "Momentum|momentum_index|momenta")
      message(FATAL_ERROR "OBC excitation report contains momentum metadata\n${output}")
    endif()
  endif()
  set(output "${output}" PARENT_SCOPE)
endfunction()

check_cli(0 "# Candidates: 3" 4 --excitations 10)
set(default_output "${output}")
check_cli(0 "# S: 1" 4 --excitations 10 --spin 1 --precision fp64 --format plain)
if(NOT output STREQUAL default_output)
  message(FATAL_ERROR "Explicit even-spin/fp64/plain defaults differ")
endif()
check_cli(0 "# S: 1/2" 5 --excitations 10)
set(default_output "${output}")
check_cli(0 "# Returned multiplets: 3" 5 --excitations 10 --spin 1/2)
if(NOT output STREQUAL default_output)
  message(FATAL_ERROR "Explicit odd-spin default differs")
endif()
check_cli(0 "# Returned multiplets: 1" 4 --excitations 1)
if(NOT output MATCHES "# Candidates: 3" OR NOT output MATCHES "# Converged candidates: 3")
  message(FATAL_ERROR "Retained count truncated the candidate scan")
endif()
check_cli(0 "NOT a complete spectrum" 4 --excitations 10 --spin 0)
check_cli(0 "# Returned multiplets: 1" 4 --excitations 10 --spin 0)
check_cli(0 "# Multiplet size: 5" 4 --excitations 10 --spin 2)
check_cli(0 "# Candidates: 1" 2 --excitations 10)
check_cli(0 "# Roots: level=1; S=1" 4 --excitations 2 --roots)
check_cli(0 "# Candidates: 3" 4 --excitations 10 --max-candidates 3)
check_cli(0 "[OK] 3/3 candidates converged" 4 --excitations 2 --format pretty)
check_cli(0 "Rapidities: level=1; S=1/2" 5 --excitations 10 --roots --format pretty)

# "all" must retain a family larger than the default numeric count, and
# produce the same ordered states as an explicit exact count in both formats.
foreach(format IN ITEMS plain pretty)
  check_cli(0 "NOT a complete spectrum" 12 --excitations 21 --spin 1 --roots --format ${format})
  set(numeric_all "${output}")
  check_cli(0 "NOT a complete spectrum" 12 --excitations all --spin 1 --roots --format ${format})
  if(NOT output STREQUAL numeric_all)
    message(FATAL_ERROR "All excitations differ from an explicit family-sized count")
  endif()
endforeach()
check_cli(0 "# Returned multiplets: 21" 12 --excitations all --max-candidates 21)
set(all_output "${output}")
check_cli(0 "# Candidates: 21" 12 --max-candidates 21 --excitations all)
if(NOT output STREQUAL all_output)
  message(FATAL_ERROR "All excitations depend on candidate-limit option order")
endif()
check_cli(0 "# Returned multiplets: 1" 4 --excitations all --spin 0)
check_cli(0 "# Returned multiplets: 1" 4 --excitations all --spin 2)
check_cli(2 "# Returned multiplets: 0" 6 --excitations all --max-iterations 0)
check_cli(2 "unavailable" 4 --excitations all --spin 2 --max-iterations 0)
check_cli(1 "exceeds max_candidates" 12 --excitations all --max-candidates 20)
check_cli(1 "exceeds max_candidates" 1000000000 --excitations all)
check_cli(1 "positive" 4 --excitations all --max-candidates 0)
check_cli(1 "invalid nonnegative integer" 4 --excitations ALL)
check_cli(1 "invalid nonnegative integer" 4 --excitations alljunk)
check_cli(1 "invalid nonnegative integer" 4 --excitations all --max-candidates all)
check_cli(1 "mutually exclusive" 4 --excitations all --sectors)

foreach(format IN ITEMS plain pretty)
  check_cli(2 "incomplete; failed candidates excluded" 6 --excitations 1 --max-iterations 0 --format ${format})
  check_cli(2 "unavailable" 4 --excitations 1 --spin 2 --max-iterations 0 --format ${format})
endforeach()
check_cli(2 "# Returned multiplets: 0" 6 --excitations 1 --max-iterations 0)
check_cli(2 "# Converged candidates: 0" 6 --excitations 1 --max-iterations 0)
check_cli(2 "# First failed I:" 6 --excitations 1 --max-iterations 0)
check_cli(2 "# Returned multiplets: 3" 4 --excitations 10 --max-iterations 1)
check_cli(2 "# Ordering: complete within supported family" 4 --excitations 10 --max-iterations 1)

check_cli(1 "require --excitations" 4 --spin 1)
check_cli(1 "require --excitations" 4 --max-candidates 100)
foreach(option IN ITEMS --excitations --spin --max-candidates)
  check_cli(1 "missing value" 4 ${option})
endforeach()
foreach(mode IN ITEMS --sz --quantum-numbers)
  check_cli(1 "mutually exclusive" 4 --excitations 2 ${mode} 1)
endforeach()
check_cli(1 "mutually exclusive" 4 --excitations 2 --sectors)
if(NOT PROGRAM MATCHES "bethe-xxx-obc")
  check_cli(1 "mutually exclusive" 5 --excitations 2 --spinons)
endif()
check_cli(1 "positive" 4 --excitations 0)
check_cli(1 "positive" 4 --excitations 2 --max-candidates 0)
check_cli(1 "exceeds max_candidates" 4 --excitations 1 --max-candidates 2)
check_cli(1 "exceeds max_candidates" 1000000000 --excitations 1)
check_cli(1 "invalid nonnegative integer" 4 --excitations -1)
check_cli(1 "invalid nonnegative integer" 4 --excitations 2junk)
check_cli(1 "invalid nonnegative integer" 4 --excitations 1 --max-candidates -1)
check_cli(1 "S must lie" 4 --excitations 1 --spin -1)
check_cli(1 "S must lie" 4 --excitations 1 --spin 3)
check_cli(1 "same half-integer parity" 4 --excitations 1 --spin 1/2)
check_cli(1 "same half-integer parity" 5 --excitations 1 --spin 1)
check_cli(1 "parse failed" 4 --excitations 1 --spin 1/4)
check_cli(1 "requires 2 <= sites" 1 --excitations 1)
check_cli(1 "finite and positive" 4 --excitations 1 --tolerance nan)

set(precisions fp64 long-double)
if(FLOAT128)
  list(APPEND precisions fp128)
else()
  check_cli(1 "fp128 is unavailable" 4 --excitations 1 --precision fp128)
endif()
foreach(precision IN LISTS precisions)
  # N=5 labels are integers, so fractional presentation cannot change the
  # decimal tokens. Gaps, reference energy/residual and roots are all checked.
  check_cli(0 "# Roots:" 5 --excitations 10 --roots --precision ${precision} --format plain)
  set(plain "${output}")
  check_cli(0 "# Returned multiplets: 3" 5 --excitations all --roots --precision ${precision} --format plain)
  if(NOT output STREQUAL plain)
    message(FATAL_ERROR "All excitations differ from oversized numeric count for ${precision}")
  endif()
  string(REGEX MATCHALL "-?[0-9]+\\.[0-9]+([eE][+-]?[0-9]+)?" tokens "${output}")
  foreach(width IN ITEMS 200 35)
    set(ENV{COLUMNS} ${width})
    check_cli(0 "NOT a complete spectrum" 5 --excitations all --roots --precision ${precision} --format pretty)
    foreach(token IN LISTS tokens)
      string(FIND "${output}" "${token}" match)
      if(match EQUAL -1)
        message(FATAL_ERROR "Lost numeric token '${token}' in ${precision} output\n${output}")
      endif()
    endforeach()
  endforeach()
  set(ENV{UNI20_COLOR} always)
  check_cli(0 "# Roots:" 5 --excitations 10 --roots --precision ${precision})
  if(NOT output STREQUAL plain)
    message(FATAL_ERROR "Auto output in a pipe differs from plain output")
  endif()
  check_cli(0 "${escape}[" 5 --excitations 1 --precision ${precision} --format pretty)
  set(ENV{UNI20_COLOR} never)
endforeach()
