include("${CMAKE_CURRENT_LIST_DIR}/check_cpu_time.cmake")
set(ENV{UNI20_COLOR} never)
set(ENV{UNI20_GLYPHS} ascii)
set(ENV{COLUMNS} 200)
function(check_cli expected_status expected_text)
  execute_process(COMMAND "${PROGRAM}" ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
  if(NOT "${status}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "Unexpected status ${status} for ${ARGN}\n${output}\n${error}")
  endif()
  string(FIND "${output}${error}" "${expected_text}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${expected_text}' for ${ARGN}\n${output}\n${error}")
  endif()
  if((expected_status EQUAL 0 OR expected_status EQUAL 2) AND NOT "--help" IN_LIST ARGN)
    normalize_cpu_time(output output)
    if(output MATCHES "Energy per site:|Sites:|Total Sz:")
      message(FATAL_ERROR "Continuum component report acquired spin-chain metadata\n${output}")
    endif()
  endif()
  set(output "${output}" PARENT_SCOPE)
endfunction()
set(base --populations 3,1,1 --length 1 --c 1)
check_cli(0 "bethe-sun-fermions-pbc" --help)
check_cli(0 "Status: converged" ${base})
set(default_output "${output}")
check_cli(0 "Precision: fp64" ${base} --precision fp64 --format plain)
if(NOT output STREQUAL default_output)
  message(FATAL_ERROR "Defaults differ from explicit fp64/plain")
endif()
check_cli(0 "Spin rapidities: level 2" ${base} --roots)
check_cli(0 "Free modes: component 1" --populations 2,1,4 --length 1 --c 0 --roots)
check_cli(0 "exact free-fermion ground state" --populations 0,6,0 --length 2 --c 10 --roots --max-iterations 0)
check_cli(0 "Total energy: 0" --populations 0,0,0 --length 1 --c 2)
check_cli(0 "Occupied components: 3" --populations 1,0,3,1 --length 1 --c 1 --roots)
check_cli(2 "Newton budget exhausted" ${base} --max-iterations 0 --roots)
if(NOT output MATCHES "Energy: unavailable: no converged coupling stage" OR output MATCHES "Total energy:|Charge momenta:")
  message(FATAL_ERROR "Unsolved seed claims roots/energy\n${output}")
endif()
check_cli(2 "Newton corrections: 1" ${base} --max-iterations 1)
check_cli(2 "stage budget exhausted" ${base} --max-stages 0)
check_cli(2 "Energy evaluated at c: 320" ${base} --max-stages 1 --roots)
foreach(option IN ITEMS --populations --length --c --precision --format --tolerance --max-iterations --max-stages)
  check_cli(1 "missing" ${base} ${option})
endforeach()
check_cli(1 "is required" --populations 1,1,1 --c 1)
execute_process(COMMAND "${PROGRAM}" --populations "" --length 1 --c 1
  RESULT_VARIABLE empty_status OUTPUT_VARIABLE empty_output ERROR_VARIABLE empty_error TIMEOUT 30)
if(NOT empty_status EQUAL 1 OR NOT empty_error MATCHES "at least one component")
  message(FATAL_ERROR "Empty list did not fail\n${empty_output}\n${empty_error}")
endif()
foreach(bad IN ITEMS 1, 1,,1 ,1)
  check_cli(1 "empty population list item" --populations ${bad} --length 1 --c 1)
endforeach()
foreach(bad IN ITEMS 2,1,1 2,2,2)
  check_cli(1 "every occupied population odd" --populations ${bad} --length 1 --c 1)
endforeach()
foreach(bad IN ITEMS 0 -1 nan inf)
  check_cli(1 "finite length>0 and c>=0" --populations 3,1,1 --c 1 --length ${bad})
  check_cli(1 "residual tolerance must be finite and positive" ${base} --tolerance ${bad})
endforeach()
foreach(bad IN ITEMS -1 nan inf)
  check_cli(1 "finite length>0 and c>=0" --populations 3,1,1 --length 1 --c ${bad})
endforeach()
check_cli(1 "not in {fp64,long-double,fp128}" ${base} --precision fp16)
check_cli(1 "not in {auto,pretty,plain}" ${base} --format json)
foreach(option IN ITEMS --sz --pbc --excitations)
  check_cli(1 "not expected" ${base} ${option})
endforeach()
set(precisions fp64 long-double)
if(FLOAT128)
  list(APPEND precisions fp128)
else()
  check_cli(1 "fp128 is unavailable" ${base} --precision fp128)
endif()
foreach(precision IN LISTS precisions)
  check_cli(0 "Total energy: 5.545117640" --populations 1,1,1 --length 1 --c 1 --precision ${precision} --roots)
  string(REGEX MATCH "Total energy: ([^\n]+)" match "${output}")
  set(energy "${CMAKE_MATCH_1}")
  set(ENV{COLUMNS} 20)
  check_cli(0 "${energy}" --populations 1,1,1 --length 1 --c 1 --precision ${precision} --roots --format pretty)
  set(ENV{COLUMNS} 200)
  check_cli(0 "Spin rapidities: level 3" --populations 3,3,3,3 --length 12 --c 0.001 --precision ${precision} --roots)
endforeach()
if(FLOAT128)
  check_cli(0 "Residual tolerance: 1.1234567890123456789012345678" ${base} --precision fp128 --tolerance 1.12345678901234567890123456789e-30)
  check_cli(0 "Length: 1.1234567890123456789012345678" --populations 3,1,1 --c 1 --precision fp128 --length 1.12345678901234567890123456789)
endif()
