include("${CMAKE_CURRENT_LIST_DIR}/check_cpu_time.cmake")
set(ENV{UNI20_COLOR} never)
set(ENV{UNI20_GLYPHS} ascii)
set(ENV{COLUMNS} 200)
function(check_cli expected_status expected_text)
  execute_process(COMMAND "${PROGRAM}" ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
  if(NOT "${status}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "Unexpected status ${status} for ${ARGN}\n${output}\n${error}")
  endif()
  string(FIND "${output}${error}" "${expected_text}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${expected_text}' for ${ARGN}\n${output}\n${error}")
  endif()
  if((expected_status EQUAL 0 OR expected_status EQUAL 2) AND NOT output MATCHES "^Usage:")
    normalize_cpu_time(output output)
    if(output MATCHES "Momentum|Sites:|Energy per site:")
      message(FATAL_ERROR "Pairing report acquired inappropriate chain metadata\n${output}")
    endif()
  endif()
  set(output "${output}" PARENT_SCOPE)
endfunction()
set(base --levels 0,1,2,3 --pairs 2 --g 1)
check_cli(0 "Usage: bethe-richardson" --help)
check_cli(0 "Status: converged" ${base})
set(default_output "${output}")
check_cli(0 "Precision: fp64" ${base} --precision fp64 --format plain)
if(NOT output STREQUAL default_output)
  message(FATAL_ERROR "Defaults differ from explicit fp64/plain")
endif()
check_cli(0 "eigenvalue variables (not occupations)" ${base} --variables)
check_cli(0 "Total energy: 4" --levels 0,1,2,3 --pairs 1 --g 0 --blocked 0,2 --variables)
check_cli(0 "Total energy: 6" --levels 0,1,2,3 --pairs 0 --g 3 --blocked 3,2,1,0)
check_cli(0 "Total energy: 0" --levels 0,1,2,3 --pairs 0 --g 3 --max-iterations 0)
check_cli(0 "Total energy: 8" --levels 0,1,2,3 --pairs 4 --g 1 --max-iterations 0)
check_cli(2 "Newton budget exhausted" ${base} --max-iterations 0)
foreach(field IN ITEMS "Reached coupling g: 0" "Energy evaluated at g: 0" "Total energy: 2" "Newton corrections: 0")
  string(FIND "${output}" "${field}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Incomplete result hides its reached coupling: ${field}\n${output}")
  endif()
endforeach()
check_cli(2 "Newton corrections: 1" ${base} --max-iterations 1)
check_cli(2 "stage budget exhausted" ${base} --max-stages 0)
foreach(option IN ITEMS --levels --pairs --g --blocked --precision --format --tolerance --max-iterations --max-stages)
  check_cli(1 "missing value" ${base} ${option})
endforeach()
check_cli(1 "are required" --levels 0,1 --g 1)
# Preserve the empty argv item explicitly; unquoted CMake list expansion
# in check_cli would remove it before the executable sees it.
execute_process(COMMAND "${PROGRAM}" --levels "" --pairs 0 --g 0
  RESULT_VARIABLE empty_status OUTPUT_VARIABLE empty_output ERROR_VARIABLE empty_error TIMEOUT 30)
if(NOT empty_status EQUAL 1 OR NOT empty_error MATCHES "at least one")
  message(FATAL_ERROR "Empty level list was not rejected: ${empty_status}\n${empty_output}\n${empty_error}")
endif()
foreach(bad IN ITEMS 1,0 0,0 nan,1 0,inf)
  check_cli(1 "finite, distinct and strictly increasing" --levels ${bad} --pairs 1 --g 1)
endforeach()
foreach(bad IN ITEMS 0, 0,,1 ,1)
  check_cli(1 "empty list item" --levels ${bad} --pairs 1 --g 1)
endforeach()
foreach(bad IN ITEMS 1,1 4)
  check_cli(1 "blocked indices must be distinct" ${base} --blocked ${bad})
endforeach()
check_cli(1 "pair count exceeds" ${base} --blocked 0,1,2)
foreach(bad IN ITEMS -1 nan inf)
  check_cli(1 "finite g>=0" --levels 0,1 --pairs 1 --g ${bad})
endforeach()
foreach(bad IN ITEMS 0 -1 nan inf)
  check_cli(1 "residual tolerance must be finite and positive" ${base} --tolerance ${bad})
endforeach()
check_cli(1 "unknown precision" ${base} --precision fp16)
check_cli(1 "unknown output format" ${base} --format json)
foreach(option IN ITEMS --roots --sz --pbc --degeneracy --excitations)
  check_cli(1 "unknown option" ${base} ${option})
endforeach()
set(precisions fp64 long-double)
if(FLOAT128)
  list(APPEND precisions fp128)
else()
  check_cli(1 "fp128 is unavailable" ${base} --precision fp128)
endif()
foreach(precision IN LISTS precisions)
  check_cli(0 "Total energy: -1.414213562373" --levels 0,1 --pairs 1 --g 1 --precision ${precision} --variables)
  string(REGEX MATCH "Total energy: ([^\n]+)" match "${output}")
  set(energy "${CMAKE_MATCH_1}")
  set(ENV{COLUMNS} 20)
  check_cli(0 "${energy}" --levels 0,1 --pairs 1 --g 1 --precision ${precision} --variables --format pretty)
  set(ENV{COLUMNS} 200)
  check_cli(0 "Reached coupling g: 20" --levels 0,.01,.013,.2,1 --pairs 2 --g 20 --precision ${precision})
endforeach()
if(FLOAT128)
  check_cli(0 "Total energy: -1.414213562373095048801688724" --levels 0,1 --pairs 1 --g 1 --precision fp128)
  check_cli(0 "Residual tolerance: 1.1234567890123456789012345678" ${base} --precision fp128 --tolerance 1.12345678901234567890123456789e-30)
endif()
