include("${CMAKE_CURRENT_LIST_DIR}/check_cpu_time.cmake")
set(ENV{UNI20_COLOR} never)
set(ENV{UNI20_GLYPHS} ascii)
set(ENV{UNI20_CHARSET} escape)
set(ENV{COLUMNS} 200)
unset(ENV{NO_COLOR})
string(ASCII 27 escape)

function(check_cli expected_status expected_text)
  execute_process(COMMAND "${PROGRAM}" ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
  if(NOT "${status}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "Unexpected status ${status} for ${ARGN}\n${output}\n${error}")
  endif()
  string(FIND "${output}${error}" "${expected_text}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${expected_text}' for ${ARGN}\n${output}\n${error}")
  endif()
  if((expected_status EQUAL 0 OR expected_status EQUAL 2) AND NOT output MATCHES "^Usage:")
    normalize_cpu_time(output output)
    if(output MATCHES "XXX|Multiplet|multiplets|# S:")
      message(FATAL_ERROR "XXZ report contains inappropriate XXX/multiplet metadata\n${output}")
    endif()
  endif()
  set(output "${output}" PARENT_SCOPE)
endfunction()

check_cli(0 "Usage: bethe-xxz-pbc" --help)
check_cli(1 "bethe-xxz-pbc: unknown option" 4 --delta 0.5 --unknown)
check_cli(0 "Total energy: -1.25" 2 --delta 0.5)
check_cli(0 "Total energy: -2" 4 --delta 1)
check_cli(0 "Total energy: -1.414213562373" 4 --delta 0)
check_cli(0 "Total energy: -1.6861406616345" 4 --delta 0.5)
set(default_output "${output}")
check_cli(0 "Precision: fp64" 4 --delta 0.5 --precision fp64 --format plain)
if(NOT output STREQUAL default_output)
  message(FATAL_ERROR "XXZ defaults differ from explicit fp64/plain")
endif()
check_cli(0 "# index rapidity I" 4 --delta 0.5 --roots)
check_cli(0 "Spin-reversed reference: 1" 5 --delta 0.5 --sz -1/2)
check_cli(0 "Sz: -1.5" 5 --delta 0.5 --sz -3/2)
check_cli(0 "Total energy: 0.625" 5 --delta 0.5 --sz 5/2 --max-iterations 0)
check_cli(0 "# Sz momentum_index P energy residual iterations converged" 5 --delta 0.5 --sectors --roots)
check_cli(0 "# Roots: Sz=-0.5" 5 --delta 0.5 --sectors --roots)
check_cli(0 "Heisenberg XXZ - ground state" 4 --delta 0.5 --format pretty)
check_cli(0 "[OK] 6/6 states converged" 5 --delta 0.5 --sectors --format pretty)
check_cli(0 "Rapidities: Sz=-1/2 (spin reversed)" 5 --delta 0.5 --sectors --roots --format pretty)
check_cli(0 "scaled rapidity z" 4 --delta 0.5 --roots --format pretty)
check_cli(0 "Iterations: 1" 4 --delta 0 --max-iterations 1)
check_cli(2 "Total energy: -2.5" 4 --delta 0.5 --max-iterations 0)
check_cli(2 "Iterations: 1" 4 --delta 0.5 --max-iterations 1)
check_cli(2 "unconverged estimate" 4 --delta 0.5 --max-iterations 0 --format pretty)
check_cli(2 "[WARN] 2/6 states converged" 5 --delta 0.5 --sectors --max-iterations 0 --format pretty)

check_cli(1 "Usage:")
check_cli(1 "--delta VALUE is required" 4)
foreach(option IN ITEMS --delta --sz --precision --tolerance --max-iterations --format --excitations --max-candidates --quantum-numbers)
  check_cli(1 "missing value" 4 ${option})
endforeach()
foreach(delta IN ITEMS -1 -2 nan inf -inf)
  check_cli(1 "finite Delta > -1" 4 --delta ${delta})
endforeach()
check_cli(0 "Total energy: -0.75" 2 --delta -0.5)
check_cli(0 "rank-subtracted equations divided by N*s" 6 --delta -0.9)
check_cli(0 "# index rapidity I lambda" 6 --delta -0.9 --sz -1 --roots)
check_cli(0 "Momentum index: 3" 6 --delta -0.9)
check_cli(0 "Momentum index: 0" 8 --delta -0.9)
check_cli(0 "converged status" 6 --delta -0.9 --sectors --roots)
check_cli(0 "[OK] 7/7 states converged" 6 --delta -0.9 --sectors --roots --format pretty)
check_cli(0 "Lambda" 6 --delta -0.9 --roots --format pretty)
check_cli(0 "Total energy: -1" 8 --delta -0.5 --sz -4 --max-iterations 0)
check_cli(2 "Iterations: 1" 8 --delta -0.5 --max-iterations 1)
check_cli(2 "unconverged estimate" 8 --delta -0.5 --max-iterations 0 --format pretty)
check_cli(2 "iteration_limit" 6 --delta -0.9 --sectors --max-iterations 0)
check_cli(2 "line search stalled; unconverged estimate" 8 --delta -0.9 --tolerance 1e-100)
check_cli(2 "line search stalled; unconverged estimate" 8 --delta -0.9 --tolerance 1e-100 --format pretty)
if(output MATCHES "iteration limit reached")
  message(FATAL_ERROR "Periodic negative XXZ stalled solve was reported as budget exhaustion\n${output}")
endif()
check_cli(1 "currently require even N" 5 --delta -0.5)
check_cli(1 "currently require even N" 5 --delta -0.5 --sectors)
check_cli(1 "currently require even N" 5 --delta -0.5 --sz 5/2)
check_cli(1 "finite Delta in [0,1]" 4 --delta -0.5 --excitations all)
check_cli(1 "finite Delta in [0,1]" 4 --delta -0.5 --quantum-numbers none)
check_cli(0 "Total energy: -2.732050807568" 4 --delta 2)
check_cli(0 "Total energy: -2.732050807568" 4 --delta 2 --sz 0)
check_cli(0 "Spin-reversed reference: 1" 5 --delta 10 --sz -1/2 --roots)
check_cli(0 "[OK] 6/6 states converged" 5 --delta 10 --sectors --roots --format pretty)
check_cli(2 "Total energy: -12" 4 --delta 10 --max-iterations 0)
check_cli(1 "finite Delta in [0,1]" 4 --delta 2 --quantum-numbers -1/2,1/2)
check_cli(1 "finite Delta in [0,1]" 4 --delta 2 --excitations all)
check_cli(1 "invalid real value" 4 --delta 0.5junk)
check_cli(1 "invalid nonnegative integer" -1 --delta 0.5)
check_cli(1 "requires 2 <= sites" 1 --delta 0.5)
check_cli(1 "invalid nonnegative integer" 4 --delta 0.5 --max-iterations -1)
check_cli(1 "Sz must lie" 4 --delta 0.5 --sz 3)
check_cli(1 "same half-integer parity" 5 --delta 0.5 --sz 0)
check_cli(1 "parse failed" 4 --delta 0.5 --sz 0.25)
check_cli(1 "mutually exclusive" 4 --delta 0.5 --sz 0 --sectors)
foreach(option IN ITEMS --spin --spinons --boundary)
  check_cli(1 "unknown option: ${option}" 4 --delta 0.5 ${option} 1)
endforeach()

check_cli(0 "# Candidates: 3" 4 --delta 0.5 --excitations all)
check_cli(0 "# Returned states: 2" 4 --delta 0.5 --excitations 2)
check_cli(0 "# Sz: 1" 4 --delta 0.5 --excitations 2)
check_cli(0 "# Sz: 1/2" 5 --delta 0.5 --excitations all)
check_cli(0 "# Returned states: 6" 6 --delta 0.5 --excitations all)
set(all_output "${output}")
check_cli(0 "# Returned states: 6" 6 --delta 0.5 --excitations 999)
if(NOT output STREQUAL all_output)
  message(FATAL_ERROR "XXZ all differs from a count exceeding family size")
endif()
check_cli(0 "# Candidates: 1" 8 --delta 0.5 --excitations all --sz 0)
check_cli(0 "# Candidates: 6" 8 --delta 0.5 --excitations all --sz 2)
check_cli(0 "# Candidates: 15" 8 --delta 0.500001 --excitations all --sz 2)
check_cli(0 "# Candidates: 15" 8 --delta 1 --excitations all --sz 2)
check_cli(0 "# Candidates: 6" 8 --delta 0 --excitations all --sz 2)
check_cli(0 "NOT a complete Sz spectrum" 8 --delta 0.5 --excitations all)
check_cli(0 "# Spin-reversed reference: 1" 6 --delta 0.5 --excitations all --sz -1)
check_cli(0 "# Roots: level=1; Sz=-1" 6 --delta 0.5 --excitations all --sz -1 --roots)
check_cli(0 "# Returned states: 1" 4 --delta 0.5 --excitations all --sz -2)
check_cli(0 "Real-root state energies" 6 --delta 0.5 --excitations all --format pretty)
check_cli(0 "3/3 candidates converged" 4 --delta 0.5 --excitations all --format pretty)
check_cli(2 "failed candidates excluded" 6 --delta 0.5 --excitations 1 --max-iterations 0)
check_cli(2 "# Returned states: 0" 6 --delta 0.5 --excitations all --max-iterations 0)
check_cli(2 "gaps unavailable" 4 --delta 0.5 --excitations all --sz 2 --max-iterations 0)
check_cli(2 "ground reference failed" 4 --delta 0.5 --excitations all --sz 2 --max-iterations 0 --format pretty)
check_cli(0 "Total energy: -1" 4 --delta 0.5 --quantum-numbers 0)
check_cli(0 "Total energy: 0.5" 4 --delta 0.5 --quantum-numbers none)
check_cli(0 "specified real-root state" 8 --delta 0.5 --quantum-numbers -3/2,1/2 --format pretty)
check_cli(1 "finite-real window" 8 --delta 0.5 --quantum-numbers -5/2,5/2)
check_cli(0 "Status: converged" 8 --delta 0.500001 --quantum-numbers -5/2,5/2)
check_cli(1 "finite-real window" 4 --delta 0 --quantum-numbers 1)
check_cli(1 "strictly increasing" 8 --delta 0.5 --quantum-numbers -1/2,-1/2)
check_cli(1 "strictly increasing" 8 --delta 0.5 --quantum-numbers 1/2,-1/2)
check_cli(1 "finite-real window" 8 --delta 0.5 --quantum-numbers 0,1)
check_cli(1 "exceeds max_candidates" 8 --delta 1 --sz 2 --excitations all --max-candidates 14)
check_cli(0 "# Candidates: 15" 8 --delta 1 --sz 2 --excitations all --max-candidates 15)
check_cli(1 "exceeds max_candidates" 1000000000 --delta 0.5 --excitations all)
check_cli(1 "must be positive" 4 --delta 0.5 --excitations 0)
check_cli(1 "must be positive" 4 --delta 0.5 --excitations all --max-candidates 0)
check_cli(1 "requires --excitations" 4 --delta 0.5 --max-candidates 100)
check_cli(1 "invalid nonnegative integer" 4 --delta 0.5 --excitations ALL)
check_cli(1 "invalid nonnegative integer" 4 --delta 0.5 --excitations -1)
check_cli(1 "mutually exclusive" 4 --delta 0.5 --excitations all --sectors)
check_cli(1 "mutually exclusive" 4 --delta 0.5 --excitations all --quantum-numbers 0)
check_cli(1 "mutually exclusive" 4 --delta 0.5 --sz 1 --quantum-numbers 0)
check_cli(1 "mutually exclusive" 4 --delta 0.5 --sectors --quantum-numbers 0)
check_cli(1 "unknown precision" 4 --delta 0.5 --precision arbitrary)
check_cli(1 "unknown output format" 4 --delta 0.5 --format arbitrary)
foreach(tol IN ITEMS 0 -1 inf nan)
  check_cli(1 "finite and positive" 4 --delta 0.5 --tolerance ${tol})
endforeach()

set(precisions fp64 long-double)
if(FLOAT128)
  list(APPEND precisions fp128)
  check_cli(0 "Total energy: -1.6861406616345071649626528670547" 4 --delta 0.5 --precision fp128)
  check_cli(0 "Delta: 0.1234567890123456789012345678" 4 --delta 0.12345678901234567890123456789 --precision fp128)
else()
  check_cli(1 "fp128 is unavailable" 4 --delta 0.5 --precision fp128)
endif()
foreach(precision IN LISTS precisions)
  foreach(negative_mode IN ITEMS single sectors)
    if(negative_mode STREQUAL single)
      set(negative_args 6)
    else()
      set(negative_args 6 --sectors)
    endif()
    check_cli(0 "# index rapidity I lambda" ${negative_args} --delta -0.5 --roots --precision ${precision} --format plain)
    string(REGEX MATCHALL "-?[0-9]+\\.[0-9]+([eE][+-]?[0-9]+)?" negative_tokens "${output}")
    list(LENGTH negative_tokens token_count)
    if(token_count LESS 5)
      message(FATAL_ERROR "Periodic negative XXZ precision check found too few numbers\n${output}")
    endif()
    foreach(width IN ITEMS 200 35)
      set(ENV{COLUMNS} ${width})
      check_cli(0 "Lambda" ${negative_args} --delta -0.5 --roots --precision ${precision} --format pretty)
      foreach(token IN LISTS negative_tokens)
        string(FIND "${output}" "${token}" match)
        if(match EQUAL -1)
          message(FATAL_ERROR "Lost periodic negative XXZ numeric token '${token}' for ${precision}\n${output}")
        endif()
      endforeach()
    endforeach()
  endforeach()
  check_cli(0 "Total energy: -2.732050807568" 4 --delta 2 --precision ${precision})
  string(REGEX MATCH "Total energy: ([^\n]+)" match "${output}")
  set(massive_energy "${CMAKE_MATCH_1}")
  set(ENV{COLUMNS} 20)
  check_cli(0 "${massive_energy}" 4 --delta 2 --precision ${precision} --roots --format pretty)
  set(ENV{COLUMNS} 200)
  # Integral Sz and quantum-number labels avoid alternate decimal/fraction
  # spellings while comparing every decimal value in the two report formats.
  foreach(mode IN ITEMS single sectors excitations)
    if(mode STREQUAL single)
      set(args 6 --sz 0)
    elseif(mode STREQUAL sectors)
      set(args 2 --sectors)
    else()
      set(args 4 --excitations all --sz -1)
    endif()
    check_cli(0 "# index rapidity I" ${args} --delta 0.5 --roots --precision ${precision} --format plain)
    set(plain "${output}")
    string(REGEX MATCHALL "-?[0-9]+\\.[0-9]+([eE][+-]?[0-9]+)?" tokens "${output}")
    foreach(width IN ITEMS 200 35)
      set(ENV{COLUMNS} ${width})
      check_cli(0 "Rapidities" ${args} --delta 0.5 --roots --precision ${precision} --format pretty)
      foreach(token IN LISTS tokens)
        string(FIND "${output}" "${token}" match)
        if(match EQUAL -1)
          message(FATAL_ERROR "Lost numeric token '${token}' for ${precision}\n${output}")
        endif()
      endforeach()
    endforeach()
    set(ENV{UNI20_COLOR} always)
    check_cli(0 "# index rapidity I" ${args} --delta 0.5 --roots --precision ${precision})
    if(NOT output STREQUAL plain)
      message(FATAL_ERROR "XXZ auto output in a pipe differs from plain output")
    endif()
    check_cli(0 "${escape}[" ${args} --delta 0.5 --roots --precision ${precision} --format pretty)
    set(ENV{UNI20_COLOR} never)
  endforeach()
endforeach()

set(ENV{UNI20_COLOR} auto)
set(ENV{NO_COLOR} 1)
check_cli(0 "Heisenberg XXZ" 4 --delta 0.5 --format pretty)
if(output MATCHES "${escape}")
  message(FATAL_ERROR "NO_COLOR left ANSI sequences")
endif()
unset(ENV{NO_COLOR})
set(ENV{UNI20_COLOR} never)
set(ENV{UNI20_GLYPHS} unicode)
set(ENV{UNI20_CHARSET} utf8)
check_cli(0 "converged" 4 --delta 0.5 --format pretty)
if(output MATCHES "\\[OK\\]")
  message(FATAL_ERROR "Unicode glyph policy ignored")
endif()
