# Exercise the real executable, including Uni20's environment-controlled policies.
include("${CMAKE_CURRENT_LIST_DIR}/check_cpu_time.cmake")
set(ENV{UNI20_GLYPHS} ascii)
set(ENV{UNI20_CHARSET} escape)
set(ENV{UNI20_COLOR} never)
set(ENV{COLUMNS} 200)
unset(ENV{NO_COLOR})
string(ASCII 27 escape)

function(run_cli expected_status)
  execute_process(COMMAND "${PROGRAM}" ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
  if(NOT "${status}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "Unexpected status ${status} for ${ARGN}\n${output}\n${error}")
  endif()
  if(expected_status EQUAL 0 OR expected_status EQUAL 2)
    normalize_cpu_time(output output)
  endif()
  set(output "${output}" PARENT_SCOPE)
endfunction()

function(require_text text)
  string(FIND "${output}" "${text}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${text}'\n${output}")
  endif()
endfunction()

function(forbid_text text)
  string(FIND "${output}" "${text}" match)
  if(NOT match EQUAL -1)
    message(FATAL_ERROR "Unexpected '${text}'\n${output}")
  endif()
endfunction()

# Apart from CPU time, captured auto output is identical to the plain format,
# even when the presentation environment would otherwise force ANSI styles.
foreach(mode IN ITEMS --sectors --spinons)
  run_cli(0 5 ${mode} --roots)
  set(plain "${output}")
  set(ENV{UNI20_COLOR} always)
  run_cli(0 5 ${mode} --roots --format plain)
  if(NOT output STREQUAL plain)
    message(FATAL_ERROR "Plain output changed with output policy")
  endif()
  run_cli(0 5 ${mode} --roots --format auto)
  if(NOT output STREQUAL plain)
    message(FATAL_ERROR "Auto output in a pipe is not plain")
  endif()
  forbid_text("${escape}")
  set(ENV{UNI20_COLOR} never)
endforeach()

run_cli(0 5 --sz -1/2 --roots --format pretty)
require_text("Heisenberg XXX - sector minimum")
require_text("[OK] converged")
require_text("-0.5")
require_text("all down (spin reversed)")
require_text("Rapidities")
require_text("Rapidity")
forbid_text("${escape}")
set(no_color_output "${output}")
set(ENV{UNI20_COLOR} auto)
set(ENV{NO_COLOR} 1)
run_cli(0 5 --sz -1/2 --roots --format pretty)
if(NOT output STREQUAL no_color_output)
  message(FATAL_ERROR "NO_COLOR output differs from color=never")
endif()
unset(ENV{NO_COLOR})
set(ENV{UNI20_COLOR} always)
run_cli(0 5 --sz -1/2 --roots --format pretty)
require_text("${escape}[")
set(ENV{UNI20_COLOR} never)

run_cli(0 4 --sz 2 --roots --format pretty)
require_text("none; fully polarized")
run_cli(0 5 --quantum-numbers -1,1 --format pretty)
require_text("specified real-root state")
run_cli(0 5 --sectors --roots --format pretty)
require_text("[OK] 6/6 states converged")
require_text("Sector energies and convergence")
require_text("Residual")
require_text("Rapidities")
run_cli(0 5 --spinons --roots --format pretty)
require_text("[OK] 3/3 states converged")
require_text("Spinon dispersion")
require_text("Lattice energies and momenta")
require_text("Rapidities")
run_cli(2 4 --max-iterations 0 --format pretty)
require_text("[WARN] iteration limit reached; unconverged estimate")
run_cli(2 5 --sectors --max-iterations 0 --format pretty)
require_text("[WARN] 2/6 states converged")
require_text("unconverged estimate")
run_cli(2 5 --spinons --max-iterations 0 --format pretty)
require_text("[WARN] 0/3 states converged")
run_cli(1 4 --format)
run_cli(1 4 --format arbitrary)

# Numeric tokens must survive pretty formatting intact at all precisions, in
# both table and narrow-terminal record layouts. N=5 has integral hole/root I
# labels, so fraction formatting does not alter any decimal tokens here.
set(precisions fp64 long-double)
if(FLOAT128)
  list(APPEND precisions fp128)
endif()
foreach(precision IN LISTS precisions)
  run_cli(0 5 --spinons --roots --precision ${precision} --format plain)
  string(REGEX MATCHALL "-?[0-9]+\\.[0-9]+([eE][+-]?[0-9]+)?" tokens "${output}")
  if(NOT tokens)
    message(FATAL_ERROR "No numeric tokens extracted")
  endif()
  foreach(width IN ITEMS 200 40)
    set(ENV{COLUMNS} ${width})
    run_cli(0 5 --spinons --roots --precision ${precision} --format pretty)
    foreach(token IN LISTS tokens)
      require_text("${token}")
    endforeach()
    if(width EQUAL 200)
      set(wide_output "${output}")
    elseif(output STREQUAL wide_output)
      message(FATAL_ERROR "Narrow terminal did not switch to record layout")
    endif()
    forbid_text("${escape}")
    if(precision STREQUAL fp128)
      require_text("1.570796326794896619231321691")
    endif()
  endforeach()
endforeach()

# Semantic glyphs also work under the Unicode policy, without forcing color.
set(ENV{UNI20_GLYPHS} unicode)
set(ENV{UNI20_CHARSET} utf8)
run_cli(0 4 --format pretty)
require_text("converged")
forbid_text("[OK]")
forbid_text("${escape}")
