include("${CMAKE_CURRENT_LIST_DIR}/check_cpu_time.cmake")
set(ENV{UNI20_COLOR} never)
set(ENV{UNI20_GLYPHS} ascii)
set(ENV{COLUMNS} 200)

function(check_cli expected_status expected_text)
  execute_process(COMMAND "${PROGRAM}" ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
  if(NOT "${status}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "Unexpected status ${status} for ${ARGN}\n${output}\n${error}")
  endif()
  string(FIND "${output}${error}" "${expected_text}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${expected_text}' for ${ARGN}\n${output}\n${error}")
  endif()
  if((expected_status EQUAL 0 OR expected_status EQUAL 2) AND NOT "--help" IN_LIST ARGN)
    normalize_cpu_time(output output)
  endif()
  set(output "${output}" PARENT_SCOPE)
endfunction()

check_cli(0 "bethe-tb-pbc" --help)
check_cli(0 "Status: converged" 4)
set(default_output "${output}")
check_cli(0 "Precision: fp64" 4 --precision fp64 --format plain)
if(NOT output STREQUAL default_output)
  message(FATAL_ERROR "Defaults differ from explicit fp64/plain")
endif()
check_cli(0 "Complex rapidities" 6 --roots)
foreach(field IN ITEMS "Spin: 1" "Total spin: 0" "Two-strings: 3" "Complex roots: 6" "Momentum index: 0" "Momentum P: 0" "Phase residual:" "Modulus residual:" "Deviated two-strings" "Deviation delta")
  string(FIND "${output}" "${field}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${field}'\n${output}")
  endif()
endforeach()
check_cli(2 "iteration limit reached; unconverged estimate" 8 --max-iterations 0 --roots)
check_cli(2 "Iterations: 1" 8 --max-iterations 1)
check_cli(2 "unconverged estimate" 8 --tolerance 1e-30)
check_cli(2 "unconverged estimate" 8 --max-iterations 0 --format pretty)
foreach(bad IN ITEMS 0 1 2 3 5 7)
  check_cli(1 "even L>=4" ${bad})
endforeach()
foreach(bad IN ITEMS -4 4.5 4junk)
  check_cli(1 "nonnegative" ${bad})
endforeach()
foreach(option IN ITEMS --precision --format --tolerance --max-iterations)
  check_cli(1 "missing" 4 ${option})
endforeach()
foreach(bad IN ITEMS 0 -1 nan inf -inf)
  check_cli(1 "residual tolerance must be finite and positive" 4 --tolerance ${bad})
endforeach()
check_cli(1 "Newton matrix is too large" 1000000000000000000)
check_cli(1 "not in {fp64,long-double,fp128}" 4 --precision fp16)
check_cli(1 "not in {auto,pretty,plain,csv,tsv,json}" 4 --format invalid)
check_cli(1 "invalid real value" 4 --tolerance 1junk)
check_cli(1 "nonnegative" 4 --max-iterations -1)
foreach(option IN ITEMS --spin --sz --sectors --excitations --delta --j --bogus)
  check_cli(1 "not expected" 4 ${option})
endforeach()
set(precisions fp64 long-double)
if(FLOAT128)
  list(APPEND precisions fp128)
else()
  check_cli(1 "fp128 is unavailable" 4 --precision fp128)
endif()
foreach(precision IN LISTS precisions)
  check_cli(0 "Total energy: -17.403124237432" 4 --precision ${precision} --roots)
  string(REGEX MATCH "Total energy: ([^\n]+)" match "${output}")
  set(energy "${CMAKE_MATCH_1}")
  set(ENV{COLUMNS} 20)
  check_cli(0 "${energy}" 4 --precision ${precision} --roots --format pretty)
  set(ENV{COLUMNS} 200)
  check_cli(0 "Status: converged" 128 --precision ${precision})
endforeach()
if(FLOAT128)
  check_cli(0 "Residual tolerance: 1.1234567890123456789012345678" 4 --precision fp128 --tolerance 1.12345678901234567890123456789e-30)
  check_cli(0 "Total energy: -17.40312423743284868648821767" 4 --precision fp128)
endif()
