include("${CMAKE_CURRENT_LIST_DIR}/check_cpu_time.cmake")
set(ENV{UNI20_COLOR} never)
set(ENV{UNI20_GLYPHS} ascii)
set(ENV{COLUMNS} 200)

function(check_cli expected_status expected_text)
  execute_process(COMMAND "${PROGRAM}" ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
  if(NOT "${status}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "Unexpected status ${status} for ${ARGN}\n${output}\n${error}")
  endif()
  string(FIND "${output}${error}" "${expected_text}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${expected_text}' for ${ARGN}\n${output}\n${error}")
  endif()
  if((expected_status EQUAL 0 OR expected_status EQUAL 2) AND NOT output MATCHES "^Usage:")
    normalize_cpu_time(output output)
    if(output MATCHES "Sz:|spin reversed|fully polarized|Charge momenta")
      message(FATAL_ERROR "SU(3) report contains unrelated spin/charge metadata\n${output}")
    endif()
  endif()
  set(output "${output}" PARENT_SCOPE)
endfunction()

check_cli(0 "Usage: bethe-su3-pbc" --help)
check_cli(0 "Status: converged" 6)
set(default_output "${output}")
check_cli(0 "Precision: fp64" 6 --format plain --precision fp64)
if(NOT output STREQUAL default_output)
  message(FATAL_ERROR "Defaults differ from explicit fp64/plain")
endif()
set(ENV{UNI20_COLOR} always)
set(ENV{COLUMNS} 20)
check_cli(0 "Status: converged" 6 --format plain)
if(NOT output STREQUAL default_output)
  message(FATAL_ERROR "Plain output changed with terminal policy")
endif()
set(ENV{UNI20_COLOR} never)
set(ENV{COLUMNS} 200)
check_cli(0 "SU(3) permutation chain (periodic)" 6 --roots --format pretty)
check_cli(0 "Color populations: 3, 3, 3" 9 --roots)
foreach(field IN ITEMS "First-level roots: 6" "Second-level roots: 3" "First-level rapidities" "Second-level rapidities" "Momentum index: 0" "Momentum P: 0" "First-level residual:" "Second-level residual:")
  string(FIND "${output}" "${field}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${field}'\n${output}")
  endif()
endforeach()
check_cli(2 "iteration limit reached; unconverged estimate" 12 --max-iterations 0 --roots)
check_cli(2 "Iterations: 1" 12 --max-iterations 1)
check_cli(2 "precision stalled; unconverged estimate" 12 --tolerance 1e-30)
check_cli(2 "unconverged estimate" 12 --max-iterations 0 --format pretty)

foreach(option IN ITEMS --precision --format --tolerance --max-iterations)
  check_cli(1 "missing value" 6 ${option})
endforeach()
foreach(bad IN ITEMS 0 1 2 4 5 7 8)
  check_cli(1 "L>=3 divisible by 3" ${bad})
endforeach()
foreach(bad IN ITEMS -3 3.5 6junk)
  check_cli(1 "invalid nonnegative integer" ${bad})
endforeach()
foreach(bad IN ITEMS 0 -1 nan inf -inf)
  check_cli(1 "residual tolerance must be finite and positive" 6 --tolerance ${bad})
endforeach()
check_cli(1 "Newton matrix is too large" 6000000000)
check_cli(1 "invalid real value" 6 --tolerance 1junk)
check_cli(1 "invalid nonnegative integer" 6 --max-iterations -1)
check_cli(1 "unknown precision" 6 --precision fp16)
check_cli(1 "unknown output format" 6 --format json)
foreach(option IN ITEMS --bogus --sz --spin --sectors --quantum-numbers --excitations --u --delta)
  check_cli(1 "unknown option" 6 ${option})
endforeach()

set(precisions fp64 long-double)
if(FLOAT128)
  list(APPEND precisions fp128)
else()
  check_cli(1 "fp128 is unavailable" 6 --precision fp128)
endif()
foreach(precision IN LISTS precisions)
  check_cli(0 "Total energy: -4.605551275463" 6 --precision ${precision} --roots)
  string(REGEX MATCH "Total energy: ([^\n]+)" match "${output}")
  set(energy "${CMAKE_MATCH_1}")
  set(ENV{COLUMNS} 20)
  check_cli(0 "${energy}" 6 --precision ${precision} --roots --format pretty)
  set(ENV{COLUMNS} 200)
  check_cli(0 "Second-level roots: 1" 3 --precision ${precision} --roots)
  check_cli(0 "Status: converged" 96 --precision ${precision})
endforeach()
if(FLOAT128)
  # Ensure parsing and rendering retain digits beyond native long double.
  check_cli(0 "Residual tolerance: 1.1234567890123456789012345678" 6 --precision fp128 --tolerance 1.12345678901234567890123456789e-30)
  check_cli(0 "Total energy: -4.605551275463989293119221267" 6 --precision fp128)
endif()
