include("${CMAKE_CURRENT_LIST_DIR}/check_cpu_time.cmake")
set(ENV{UNI20_COLOR} never)
set(ENV{UNI20_GLYPHS} ascii)
set(ENV{COLUMNS} 200)
function(check_cli expected_status expected_text)
  execute_process(COMMAND "${PROGRAM}" ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
  if(NOT "${status}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "Unexpected status ${status} for ${ARGN}\n${output}\n${error}")
  endif()
  string(FIND "${output}${error}" "${expected_text}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${expected_text}' for ${ARGN}\n${output}\n${error}")
  endif()
  if((expected_status EQUAL 0 OR expected_status EQUAL 2) AND NOT "--help" IN_LIST ARGN)
    normalize_cpu_time(output output)
    if(output MATCHES "Momentum|Energy per site:")
      message(FATAL_ERROR "Central-spin report acquired inappropriate chain metadata\n${output}")
    endif()
  endif()
  set(output "${output}" PARENT_SCOPE)
endfunction()
set(base --couplings 1,0.7,0.3 --field 1 --sz 0)
check_cli(0 "bethe-central-spin" --help)
check_cli(0 "Status: converged" ${base})
set(default_output "${output}")
check_cli(0 "Precision: fp64" ${base} --precision fp64 --format plain)
if(NOT output STREQUAL default_output)
  message(FATAL_ERROR "Defaults differ from explicit fp64/plain")
endif()
check_cli(0 "Eigenvalue variables (not occupations" ${base} --variables)
check_cli(0 "Spin reversed: yes" --couplings 1,0.7,0.3 --sz 0 --field -1)
check_cli(0 "Energy evaluated at B: 0" --couplings 1,0.7,0.3 --sz 0 --field 0)
check_cli(0 "Total energy: -0.5" --couplings 1,0.7,0.3 --field -2 --sz 2 --max-iterations 0)
check_cli(2 "Newton budget exhausted" ${base} --max-iterations 0)
if(NOT output MATCHES "Energy: unavailable: no finite-field stage reached" OR output MATCHES "Total energy:")
  message(FATAL_ERROR "Infinite-field seed claims an energy\n${output}")
endif()
check_cli(2 "Newton corrections: 1" ${base} --max-iterations 1)
check_cli(2 "stage budget exhausted" ${base} --max-stages 0)
check_cli(2 "Energy evaluated at B:" ${base} --max-stages 1)
if(output MATCHES "Energy evaluated at B: 1\n")
  message(FATAL_ERROR "Partial solve attributes its energy to the requested field\n${output}")
endif()
foreach(option IN ITEMS --couplings --field --sz --precision --format --tolerance --max-iterations --max-stages)
  check_cli(1 "missing" ${base} ${option})
endforeach()
check_cli(1 "is required" --couplings 1 --field 1)
execute_process(COMMAND "${PROGRAM}" --couplings "" --field 3 --sz -1/2 --format plain
  RESULT_VARIABLE empty_status OUTPUT_VARIABLE empty_output ERROR_VARIABLE empty_error TIMEOUT 30)
if(NOT empty_status EQUAL 0 OR NOT empty_output MATCHES "Total energy: -1.5")
  message(FATAL_ERROR "Isolated central spin failed\n${empty_output}\n${empty_error}")
endif()
check_cli(1 "repeated bath couplings" --couplings 1,1,2 --field 1 --sz 0)
foreach(bad IN ITEMS 0 nan inf)
  check_cli(1 "finite, distinct and nonzero" --couplings ${bad} --field 1 --sz 0)
endforeach()
foreach(bad IN ITEMS 1, 1,,2 ,1)
  check_cli(1 "empty coupling list item" --couplings ${bad} --field 1 --sz 0)
endforeach()
foreach(bad IN ITEMS nan inf)
  check_cli(1 "field must be finite" --couplings 1,0.7,0.3 --sz 0 --field ${bad})
endforeach()
foreach(bad IN ITEMS 0 -1 nan inf)
  check_cli(1 "residual tolerance must be finite and positive" ${base} --tolerance ${bad})
endforeach()
check_cli(1 "physical total spin projection" --couplings 1,0.7,0.3 --field 1 --sz 1/2)
check_cli(1 "physical total spin projection" --couplings 1,0.7,0.3 --field 1 --sz 3)
check_cli(1 "not in {fp64,long-double,fp128}" ${base} --precision fp16)
check_cli(1 "not in {auto,pretty,plain,csv,tsv,json}" ${base} --format invalid)
foreach(option IN ITEMS --roots --pbc --excitations)
  check_cli(1 "not expected" ${base} ${option})
endforeach()
set(precisions fp64 long-double)
if(FLOAT128)
  list(APPEND precisions fp128)
else()
  check_cli(1 "fp128 is unavailable" ${base} --precision fp128)
endif()
foreach(precision IN LISTS precisions)
  check_cli(0 "Total energy: -0.957106781186" --couplings 1 --field 1 --sz 0 --precision ${precision} --variables)
  string(REGEX MATCH "Total energy: ([^\n]+)" match "${output}")
  set(energy "${CMAKE_MATCH_1}")
  set(ENV{COLUMNS} 20)
  check_cli(0 "${energy}" --couplings 1 --field 1 --sz 0 --precision ${precision} --variables --format pretty)
  set(ENV{COLUMNS} 200)
  check_cli(0 "Total energy: -0.75" --couplings 1 --field 0 --sz 0 --precision ${precision})
endforeach()
if(FLOAT128)
  check_cli(0 "Total energy: -0.957106781186547524400844362" --couplings 1 --field 1 --sz 0 --precision fp128)
  check_cli(0 "Residual tolerance: 1.1234567890123456789012345678" ${base} --precision fp128 --tolerance 1.12345678901234567890123456789e-30)
endif()
