include("${CMAKE_CURRENT_LIST_DIR}/check_cpu_time.cmake")
set(ENV{UNI20_COLOR} never)
set(ENV{UNI20_GLYPHS} ascii)
set(ENV{COLUMNS} 200)
function(check_cli expected_status expected_text)
  execute_process(COMMAND "${PROGRAM}" ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
  if(NOT "${status}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "Unexpected status ${status} for ${ARGN}\n${output}\n${error}")
  endif()
  string(FIND "${output}${error}" "${expected_text}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${expected_text}' for ${ARGN}\n${output}\n${error}")
  endif()
  if((expected_status EQUAL 0 OR expected_status EQUAL 2) AND NOT output MATCHES "^Usage:")
    normalize_cpu_time(output output)
  endif()
  set(output "${output}" PARENT_SCOPE)
endfunction()
check_cli(0 "Usage: bethe-ladder-pbc" --help)
check_cli(0 "Status: converged" 6 --rung 1)
set(default_output "${output}")
check_cli(0 "Precision: fp64" 6 --rung 1 --precision fp64 --format plain)
if(NOT output STREQUAL default_output)
  message(FATAL_ERROR "Defaults differ from explicit fp64/plain")
endif()
check_cli(0 "Singlet-sector minima" 6 --rung -1 --sectors --roots)
check_cli(0 "SU(4) descendant: yes" 6 --rung 0 --singlets 4 --roots)
check_cli(0 "Highest-weight rows: 4, 2, 0, 0" 6 --rung 0 --singlets 4)
check_cli(0 "Exact limit: rung-singlet product" 12 --rung 4 --max-iterations 0 --max-branches 0)
check_cli(0 "Total energy: 9" 6 --rung -1 --singlets 6 --max-iterations 0 --max-branches 0)
check_cli(2 "Newton budget exhausted" 6 --rung 0 --max-iterations 0 --roots)
if(NOT output MATCHES "Candidate energy \\(upper bound\\):" OR output MATCHES "Total energy:")
  message(FATAL_ERROR "Incomplete scan claims a ground state\n${output}")
endif()
# The one-root sea lambda=0 already solves its equations without Newton work.
if(NOT output MATCHES "Highest-weight rows: 5, 1, 0, 0" OR output MATCHES "Highest-weight rapidities: level 2")
  message(FATAL_ERROR "Zero budget exposed an unsolved seed\n${output}")
endif()
check_cli(2 "Newton corrections: 1" 6 --rung 0 --max-iterations 1)
check_cli(2 "Energy: unavailable: no converged branch" 6 --rung 0 --max-branches 0 --roots)
check_cli(2 "Singlet-sector candidate upper bounds" 6 --rung 0 --sectors --max-branches 1)
check_cli(1 "--rung is required" 6)
check_cli(1 "mutually exclusive" 6 --rung 0 --singlets 1 --sectors)
check_cli(1 "singlet count must not exceed" 6 --rung 0 --singlets 7)
check_cli(1 "2<=rungs" 1 --rung 0)
foreach(option IN ITEMS --rung --singlets --precision --format --tolerance --max-iterations --max-branches)
  check_cli(1 "missing value" 6 --rung 0 ${option})
endforeach()
foreach(bad IN ITEMS nan inf -inf)
  check_cli(1 "rung coupling must be finite" 6 --rung ${bad})
endforeach()
foreach(bad IN ITEMS 0 -1 nan inf)
  check_cli(1 "residual tolerance must be finite and positive" 6 --rung 0 --tolerance ${bad})
endforeach()
check_cli(1 "unknown precision" 6 --rung 0 --precision fp16)
check_cli(1 "unknown output format" 6 --rung 0 --format json)
foreach(option IN ITEMS --sz --field --excitations)
  check_cli(1 "unknown option" 6 --rung 0 ${option})
endforeach()
set(precisions fp64 long-double)
if(FLOAT128)
  list(APPEND precisions fp128)
else()
  check_cli(1 "fp128 is unavailable" 6 --rung 0 --precision fp128)
endif()
foreach(precision IN LISTS precisions)
  check_cli(0 "Total energy: -6.105551275" 6 --rung 0 --singlets 2 --precision ${precision} --roots)
  string(REGEX MATCH "Total energy: ([^\n]+)" match "${output}")
  set(energy "${CMAKE_MATCH_1}")
  set(ENV{COLUMNS} 20)
  check_cli(0 "${energy}" 6 --rung 0 --singlets 2 --precision ${precision} --roots --format pretty)
  set(ENV{COLUMNS} 200)
  check_cli(0 "Highest-weight rapidities: level 3" 8 --rung 0 --precision ${precision} --roots)
endforeach()
if(FLOAT128)
  check_cli(0 "Residual tolerance: 1.1234567890123456789012345678" 6 --rung 0 --precision fp128 --tolerance 1.12345678901234567890123456789e-30)
  check_cli(0 "Rung coupling J_r: 1.1234567890123456789012345678" 6 --rung 1.12345678901234567890123456789 --precision fp128)
endif()
