function(check_cli expected_status expected_text)
  execute_process(COMMAND "${PROGRAM}" ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
  if(NOT "${status}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "Unexpected status ${status} for ${ARGN}\n${output}\n${error}")
  endif()
  string(FIND "${output}${error}" "${expected_text}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${expected_text}' for ${ARGN}\n${output}\n${error}")
  endif()
endfunction()

check_cli(0 "Usage:" --help)
check_cli(0 "Total energy: -1.5" 2)
check_cli(0 "Precision: fp64" 4 --precision fp64)
check_cli(0 "# index rapidity" 4 --roots)
check_cli(0 "Residual tolerance:" 16 --tolerance 1e-10)
check_cli(2 "unconverged estimate" 16 --max-iterations 1)
check_cli(2 "Iterations: 0" 4 --max-iterations 0)
check_cli(1 "Usage:")
check_cli(1 "even number of sites" 3)
check_cli(1 "even number of sites" 0)
check_cli(1 "invalid nonnegative integer" -4)
check_cli(1 "invalid nonnegative integer" 4junk)
check_cli(1 "invalid nonnegative integer" 999999999999999999999999999999)
check_cli(1 "invalid nonnegative integer" 4 --max-iterations -1)
check_cli(1 "unknown option" 4 --unknown)
check_cli(1 "missing value" 4 --precision)
check_cli(1 "unknown precision" 4 --precision arbitrary)
check_cli(1 "finite and positive" 4 --tolerance 0)
check_cli(1 "finite and positive" 4 --tolerance -1)
check_cli(1 "finite and positive" 4 --tolerance nan)
check_cli(1 "finite and positive" 4 --tolerance inf)
check_cli(1 "invalid real value" 4 --tolerance 1e-10junk)
if(FLOAT128)
  # The analytic N=6 energy is -(2+sqrt(13))/2. Require digits far beyond
  # double or x87 precision from the actual executable, not just the library.
  check_cli(0 "Total energy: -2.8027756377319946465596106337" 6 --precision fp128)
else()
  check_cli(1 "fp128 is unavailable" 6 --precision fp128)
endif()
