include("${CMAKE_CURRENT_LIST_DIR}/check_cpu_time.cmake")
set(ENV{UNI20_COLOR} never)
set(ENV{UNI20_GLYPHS} ascii)
set(ENV{UNI20_CHARSET} escape)
set(ENV{COLUMNS} 132)

function(check_cli expected_status expected_text)
  execute_process(COMMAND "${PROGRAM}" ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
  if(NOT "${status}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "Unexpected status ${status} for ${ARGN}\n${output}\n${error}")
  endif()
  string(FIND "${output}${error}" "${expected_text}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${expected_text}' for ${ARGN}\n${output}\n${error}")
  endif()
  if((expected_status EQUAL 0 OR expected_status EQUAL 2) AND NOT "--help" IN_LIST ARGN)
    normalize_cpu_time(output output)
    if(output MATCHES "Momentum|momentum_index|momenta")
      message(FATAL_ERROR "Open-chain report contains periodic momentum metadata\n${output}")
    endif()
  endif()
  set(output "${output}" PARENT_SCOPE)
endfunction()

check_cli(0 "bethe-xxx-obc" --help)
check_cli(1 "not expected" 4 --unknown)
check_cli(0 "Total energy: -0.75" 2)
check_cli(0 "Precision: fp64" 4)
set(default_output "${output}")
check_cli(0 "Precision: fp64" 4 --precision fp64)
if(NOT output STREQUAL default_output)
  message(FATAL_ERROR "Open default output differs from explicit fp64")
endif()
check_cli(0 "Total energy: -1.6160254037844" 4)
check_cli(0 "Sz: 0.5" 3)
check_cli(0 "Precision: long-double" 4 --precision long-double)
check_cli(0 "Rapidities" 4 --roots)
check_cli(0 "Sz: -1.5" 5 --sz -3/2)
check_cli(0 "Spin-reversed reference: 1" 5 --sz -1/2)
check_cli(0 "Total energy: 0.75" 4 --sz 2 --max-iterations 0)
check_cli(0 "Sector energies and convergence" 5 --sectors --roots)
set(plain "${output}")
check_cli(0 "Rapidities" 5 --sectors --roots --format plain)
if(NOT output STREQUAL plain)
  message(FATAL_ERROR "Open auto output in a pipe differs from plain output")
endif()
check_cli(0 "Sz: 1" 4 --quantum-numbers 1)
check_cli(0 "Total energy: -1.6160254037844" 4 --quantum-numbers 1,2)
check_cli(0 "Sz: 0" 4 --quantum-numbers 1.0,2.0)

check_cli(0 "open spin-1/2, free ends" 4 --roots --format pretty)
check_cli(0 "[OK] 6/6 states converged" 5 --sectors --format pretty)
check_cli(0 "Rapidities" 5 --sectors --roots --format pretty)
check_cli(2 "unconverged estimate" 4 --max-iterations 0)
check_cli(2 "Iterations: 1" 4 --max-iterations 1)
check_cli(2 "unconverged estimate" 5 --sectors --max-iterations 0)
check_cli(2 "[WARN] 2/6 states converged" 5 --sectors --max-iterations 0 --format pretty)

check_cli(1 "Usage")
check_cli(1 "requires 2 <= sites" 1)
check_cli(1 "nonnegative" -1)
check_cli(1 "nonnegative" 4junk)
check_cli(1 "nonnegative" 4 --max-iterations -1)
check_cli(1 "same half-integer parity" 5 --sz 0)
check_cli(1 "Sz must lie" 4 --sz 3)
check_cli(1 "parse failed" 4 --sz 0.25)
check_cli(1 "integers in [1,N-M]" 4 --quantum-numbers 0)
check_cli(1 "integers in [1,N-M]" 4 --quantum-numbers -1)
check_cli(1 "integers in [1,N-M]" 4 --quantum-numbers 1/2)
check_cli(1 "integers in [1,N-M]" 4 --quantum-numbers 1,3)
check_cli(1 "strictly increasing" 4 --quantum-numbers 2,1)
check_cli(1 "strictly increasing" 4 --quantum-numbers 1,1)
check_cli(1 "M <= N/2" 4 --quantum-numbers 1,2,3)
check_cli(1 "parse failed" 4 --quantum-numbers 1,)
check_cli(1 "mutually exclusive" 4 --sectors --sz 0)
check_cli(1 "mutually exclusive" 4 --sectors --quantum-numbers 1,2)
check_cli(1 "not expected" 5 --spinons)
check_cli(1 "not expected" 4 --boundary periodic)
check_cli(1 "missing" 4 --precision)
check_cli(1 "missing" 4 --sz)
check_cli(1 "not in {fp64,long-double,fp128}" 4 --precision arbitrary)
check_cli(1 "not in {auto,pretty,plain,csv,tsv,json}" 4 --format arbitrary)
check_cli(1 "finite and positive" 4 --tolerance 0)
check_cli(1 "finite and positive" 4 --tolerance -1)
check_cli(1 "finite and positive" 4 --tolerance inf)
check_cli(1 "finite and positive" 4 --tolerance nan)
check_cli(1 "invalid real value" 4 --tolerance 1e-10junk)

set(precisions fp64 long-double)
if(FLOAT128)
  list(APPEND precisions fp128)
  check_cli(0 "Total energy: -1.6160254037844386467637231707529" 4 --precision fp128)
else()
  check_cli(1 "fp128 is unavailable" 4 --precision fp128)
endif()
foreach(precision IN LISTS precisions)
  check_cli(0 "Rapidities" 4 --precision ${precision} --roots --format plain)
  string(REGEX MATCHALL "-?[0-9]+\\.[0-9]+([eE][+-]?[0-9]+)?" tokens "${output}")
  foreach(width IN ITEMS 132 35)
    set(ENV{COLUMNS} ${width})
    check_cli(0 "Rapidities" 4 --precision ${precision} --roots --format pretty)
    foreach(token IN LISTS tokens)
      string(FIND "${output}" "${token}" match)
      if(match EQUAL -1)
        message(FATAL_ERROR "Lost precision token '${token}'\n${output}")
      endif()
    endforeach()
  endforeach()
endforeach()
