include("${CMAKE_CURRENT_LIST_DIR}/check_cpu_time.cmake")
set(ENV{UNI20_COLOR} never)
set(ENV{UNI20_GLYPHS} ascii)
set(ENV{COLUMNS} 200)

function(check_cli expected_status expected_text)
  execute_process(COMMAND "${PROGRAM}" ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
  if(NOT "${status}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "Unexpected status ${status} for ${ARGN}\n${output}\n${error}")
  endif()
  string(FIND "${output}${error}" "${expected_text}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${expected_text}' for ${ARGN}\n${output}\n${error}")
  endif()
  if((expected_status EQUAL 0 OR expected_status EQUAL 2) AND NOT "--help" IN_LIST ARGN)
    normalize_cpu_time(output output)
    if(output MATCHES "Sites:|Energy per site:|Brillouin")
      message(FATAL_ERROR "Continuum report contains lattice metadata\n${output}")
    endif()
  endif()
  set(output "${output}" PARENT_SCOPE)
endfunction()

check_cli(0 "bethe-gaudin-yang-pbc" --help)
check_cli(0 "Status: converged" 6 --length 6 --c 1)
set(default_output "${output}")
check_cli(0 "Precision: fp64" 6 --length 6 --c 1 --format plain --precision fp64 --sz 0)
if(NOT output STREQUAL default_output)
  message(FATAL_ERROR "Defaults differ from explicit fp64/plain/Sz=0")
endif()
set(ENV{UNI20_COLOR} always)
set(ENV{COLUMNS} 20)
check_cli(0 "Status: converged" 6 --length 6 --c 1 --format plain)
if(NOT output STREQUAL default_output)
  message(FATAL_ERROR "Plain output changed with terminal policy")
endif()
set(ENV{UNI20_COLOR} never)
set(ENV{COLUMNS} 200)
check_cli(0 "Gaudin-Yang gas (periodic)" 6 --length 6 --c 1 --roots --format pretty)
check_cli(0 "Reference spin: down (spin reversed)" 8 --length 8 --c 1 --sz -1 --roots)
foreach(field IN ITEMS "N_up: 3" "N_down: 5" "Spin roots: 3" "Charge momenta" "Spin rapidities" "Momentum index: 0" "Charge residual:" "Spin residual:" "Root coupling reached:")
  string(FIND "${output}" "${field}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${field}'\n${output}")
  endif()
endforeach()
check_cli(0 "Free up-spin modes" 4 --length 2 --c 0 --roots)
if(output MATCHES "Spin rapidities|Charge momenta|Reference spin:")
  message(FATAL_ERROR "Free occupations incorrectly labeled as interacting roots\n${output}")
endif()
check_cli(0 "Momentum index: 2" 4 --length 2 --c 0)
check_cli(0 "Total energy: 0" 0 --length 1 --c 100 --roots)
check_cli(0 "Total energy: 0" 1 --length 1 --c 100 --roots)
check_cli(0 "exact free-fermion ground state" 5 --length 1 --c 100 --sz -5/2 --roots)
check_cli(0 "Sz: 1/2" 3 --length 1 --c 0)
check_cli(2 "iteration limit reached; unconverged estimate" 6 --length 1 --c 1 --max-iterations 0 --roots)
check_cli(2 "Iterations: 1" 6 --length 1 --c 1 --max-iterations 1)
check_cli(2 "precision stalled; unconverged estimate" 6 --length 1 --c 1 --tolerance 1e-40)
check_cli(2 "unconverged estimate" 6 --length 1 --c 1 --max-iterations 0 --format pretty)

foreach(option IN ITEMS --length --c --sz --precision --format --tolerance --max-iterations)
  check_cli(1 "missing" 6 ${option})
endforeach()
check_cli(1 "is required" 6)
check_cli(1 "is required" 6 --length 1)
check_cli(1 "is required" 6 --c 1)
foreach(n IN ITEMS 3 4 5 8)
  check_cli(1 "requires odd N_up and N_down" ${n} --length 1 --c 1)
endforeach()
foreach(sz IN ITEMS -4 4 1/2 -1/2)
  check_cli(1 "same parity as N" 6 --length 1 --c 1 --sz ${sz})
endforeach()
foreach(bad IN ITEMS -1 nan inf -inf)
  check_cli(1 "finite length > 0 and c >= 0" 6 --length 1 --c ${bad})
  check_cli(1 "finite length > 0 and c >= 0" 6 --length ${bad} --c 1)
endforeach()
check_cli(1 "finite length > 0" 6 --length 0 --c 1)
foreach(bad IN ITEMS 0 -1 nan inf -inf)
  check_cli(1 "residual tolerance must be finite and positive" 6 --length 1 --c 1 --tolerance ${bad})
endforeach()
check_cli(1 "invalid real value" 6 --length 1junk --c 1)
check_cli(1 "nonnegative" -1 --length 1 --c 1)
check_cli(1 "quantum-number range" 9223372036854775807 --length 1 --c 1)
check_cli(1 "Newton matrix is too large" 6000000002 --length 1 --c 1 --sz 3000000000)
check_cli(1 "not in {fp64,long-double,fp128}" 6 --length 1 --c 1 --precision fp16)
check_cli(1 "not in {auto,pretty,plain}" 6 --length 1 --c 1 --format json)
foreach(option IN ITEMS --bogus --sectors --quantum-numbers --excitations --u --delta)
  check_cli(1 "not expected" 6 --length 1 --c 1 ${option})
endforeach()

set(precisions fp64 long-double)
if(FLOAT128)
  list(APPEND precisions fp128)
else()
  check_cli(1 "fp128 is unavailable" 6 --length 1 --c 1 --precision fp128)
endif()
foreach(precision IN LISTS precisions)
  check_cli(0 "Status: converged" 6 --length 6 --c 1 --precision ${precision} --roots)
  string(REGEX MATCH "Total energy: ([^\n]+)" match "${output}")
  set(energy "${CMAKE_MATCH_1}")
  set(ENV{COLUMNS} 20)
  check_cli(0 "${energy}" 6 --length 6 --c 1 --precision ${precision} --roots --format pretty)
  set(ENV{COLUMNS} 200)
  check_cli(0 "Status: converged" 18 --length 18 --c 0.001 --precision ${precision})
  check_cli(0 "Status: converged" 18 --length 18 --c 100000 --precision ${precision})
endforeach()
if(FLOAT128)
  check_cli(0 "c: 1.1234567890123456789012345678" 6 --length 6 --c 1.12345678901234567890123456789 --precision fp128)
  check_cli(0 "Length: 6.1234567890123456789012345678" 6 --length 6.12345678901234567890123456789 --c 1 --precision fp128)
endif()
