include("${CMAKE_CURRENT_LIST_DIR}/check_cpu_time.cmake")
set(ENV{UNI20_COLOR} never)
set(ENV{UNI20_GLYPHS} ascii)
set(ENV{COLUMNS} 200)

function(check_cli expected_status expected_text)
  execute_process(COMMAND "${PROGRAM}" ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
  if(NOT "${status}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "Unexpected status ${status} for ${ARGN}\n${output}\n${error}")
  endif()
  string(FIND "${output}${error}" "${expected_text}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${expected_text}' for ${ARGN}\n${output}\n${error}")
  endif()
  if((expected_status EQUAL 0 OR expected_status EQUAL 2) AND NOT "--help" IN_LIST ARGN)
    normalize_cpu_time(output output)
    if(output MATCHES "Sites:|Sz:|spin reversed|fully polarized|Energy per site")
      message(FATAL_ERROR "Continuum report contains inappropriate lattice metadata\n${output}")
    endif()
  endif()
  set(output "${output}" PARENT_SCOPE)
endfunction()

check_cli(0 "bethe-lieb-liniger-pbc" --help)
check_cli(0 "Status: converged" 4 --length 4 --c 1)
set(default_output "${output}")
check_cli(0 "Precision: fp64" 4 --length 4 --c 1 --format plain --precision fp64)
if(NOT output STREQUAL default_output)
  message(FATAL_ERROR "Defaults differ from explicit fp64/plain")
endif()
set(ENV{UNI20_COLOR} always)
check_cli(0 "Status: converged" 4 --length 4 --c 1 --format plain)
if(NOT output STREQUAL default_output)
  message(FATAL_ERROR "Plain output changed with terminal policy")
endif()
set(ENV{UNI20_COLOR} never)
check_cli(0 "Lieb-Liniger (periodic)" 4 --length 4 --c 1 --roots --format pretty)
check_cli(0 "Physical momenta" 4 --length 4 --c 1 --roots)
check_cli(0 "Total energy: 0" 0 --length 4 --c 1 --quantum-numbers none --roots)
check_cli(0 "Momentum index: -3" 1 --length 3 --c 1 --quantum-numbers -3 --max-iterations 0)
check_cli(0 "Candidate count: 15" 4 --length 4 --c 1 --excitations all --padding 1)
check_cli(0 "Retained count: 15" 4 --length 4 --c 1 --excitations all --padding 1 --max-candidates 15)
check_cli(0 "Retained count: 2" 4 --length 4 --c 1 --excitations 2 --padding 1 --roots)
check_cli(0 "Candidate count: 1" 4 --length 4 --c 1 --excitations all --padding 0)
check_cli(0 "Candidate count: 1" 0 --length 4 --c 1 --excitations all --padding 2)
check_cli(0 "Converged levels" 3 --length 3 --c 1 --excitations all --padding 1 --roots --format pretty)
check_cli(2 "iteration limit reached; unconverged estimate" 4 --length 4 --c 1 --max-iterations 0)
check_cli(2 "Iterations: 1" 4 --length 4 --c 1 --max-iterations 1)
check_cli(2 "precision stalled; unconverged estimate" 4 --length 4 --c 1 --tolerance 1e-30)
check_cli(2 "Retained count: 0" 4 --length 4 --c 1 --max-iterations 0 --excitations all --padding 1)
check_cli(2 "First failed Status: iteration limit" 4 --length 4 --c 1 --max-iterations 0 --excitations 1 --padding 1 --roots)
check_cli(2 "unconverged" 4 --length 4 --c 1 --max-iterations 0 --excitations all --padding 1 --format pretty)

check_cli(1 "is required" 4)
foreach(option IN ITEMS --length --c --quantum-numbers --excitations --padding --max-candidates --precision --format --tolerance --max-iterations)
  check_cli(1 "missing" 4 --length 4 --c 1 ${option})
endforeach()
foreach(bad IN ITEMS 0 -1 nan inf -inf)
  check_cli(1 "finite length > 0 and c > 0" 4 --length ${bad} --c 1)
  check_cli(1 "finite length > 0 and c > 0" 4 --length 4 --c ${bad})
  check_cli(1 "residual tolerance must be finite and positive" 4 --length 4 --c 1 --tolerance ${bad})
endforeach()
check_cli(1 "requires an explicit --padding" 4 --length 4 --c 1 --excitations all)
check_cli(1 "require --excitations" 4 --length 4 --c 1 --padding 1)
check_cli(1 "require --excitations" 4 --length 4 --c 1 --max-candidates 10)
check_cli(1 "cannot be combined" 4 --length 4 --c 1 --excitations all --padding 0 --quantum-numbers none)
check_cli(1 "must be positive" 4 --length 4 --c 1 --excitations 0 --padding 0)
check_cli(1 "must be positive" 4 --length 4 --c 1 --excitations all --padding 0 --max-candidates 0)
check_cli(1 "exceeds max_candidates" 4 --length 4 --c 1 --excitations all --padding 1 --max-candidates 14)
check_cli(1 "exceeds max_candidates" 1000 --length 1 --c 1 --excitations all --padding 1000)
check_cli(1 "Newton matrix is too large" 2000000000 --length 1 --c 1)
check_cli(1 "strictly increasing integers" 2 --length 1 --c 1 --quantum-numbers 0,1)
check_cli(1 "strictly increasing integers" 3 --length 1 --c 1 --quantum-numbers 0,0,1)
check_cli(1 "count must equal N" 2 --length 1 --c 1 --quantum-numbers none)
check_cli(1 "invalid real value" 2 --length 1junk --c 1)
check_cli(1 "not in {fp64,long-double,fp128}" 2 --length 1 --c 1 --precision fp16)
check_cli(1 "not in {auto,pretty,plain,csv,tsv,json}" 2 --length 1 --c 1 --format invalid)
check_cli(1 "not expected" 2 --length 1 --c 1 --bogus)

set(precisions fp64 long-double)
if(FLOAT128)
  list(APPEND precisions fp128)
else()
  check_cli(1 "fp128 is unavailable" 2 --length 1 --c 1 --precision fp128)
endif()
foreach(precision IN LISTS precisions)
  check_cli(0 "Total energy: 4.934802200544" 2 --length 1 --c 3.141592653589793238462643383279502884 --precision ${precision} --roots)
  string(REGEX MATCH "Total energy: ([^\n]+)" match "${output}")
  set(energy "${CMAKE_MATCH_1}")
  set(ENV{COLUMNS} 20)
  check_cli(0 "${energy}" 2 --length 1 --c 3.141592653589793238462643383279502884 --precision ${precision} --roots --format pretty)
  set(ENV{COLUMNS} 200)
  check_cli(0 "Status: converged" 8 --length 1 --c 1e-40 --precision ${precision})
  check_cli(0 "Retained count: 15" 4 --length 4 --c 1 --precision ${precision} --excitations all --padding 1)
endforeach()
if(FLOAT128)
  # Check digits beyond long-double precision, allowing final binary rounding.
  check_cli(0 "Length: 4.1234567890123456789012345678" 2 --length 4.12345678901234567890123456789 --c 1 --precision fp128)
endif()
