include("${CMAKE_CURRENT_LIST_DIR}/check_cpu_time.cmake")

function(check_cli expected_status expected_text)
  execute_process(COMMAND "${PROGRAM}" ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
  if(NOT "${status}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "Unexpected status ${status} for ${ARGN}\n${output}\n${error}")
  endif()
  string(FIND "${output}${error}" "${expected_text}" match)
  if(match EQUAL -1)
    message(FATAL_ERROR "Missing '${expected_text}' for ${ARGN}\n${output}\n${error}")
  endif()
  if((expected_status EQUAL 0 OR expected_status EQUAL 2) AND NOT "--help" IN_LIST ARGN)
    normalize_cpu_time(output output)
  endif()
  set(cli_output "${output}" PARENT_SCOPE)
endfunction()

check_cli(0 "bethe-xxx-pbc" --help)
check_cli(1 "not expected" 4 --unknown)
check_cli(0 "default: fp64" --help)
check_cli(0 "Precision: fp64" 6)
set(default_output "${cli_output}")
check_cli(0 "Precision: fp64" 6 --precision fp64)
if(NOT cli_output STREQUAL default_output)
  message(FATAL_ERROR "Default precision output differs from explicit fp64")
endif()
check_cli(0 "Precision: long-double" 6 --precision long-double)
check_cli(0 "Total energy: -1.5" 2)
check_cli(0 "Precision: fp64" 4 --precision fp64)
check_cli(0 "# index rapidity" 4 --roots)
check_cli(0 "Residual tolerance:" 16 --tolerance 1e-10)
check_cli(2 "unconverged estimate" 16 --max-iterations 1)
check_cli(2 "Iterations: 0" 4 --max-iterations 0)
check_cli(1 "Usage")
check_cli(0 "Sz: 0.5" 3)
check_cli(1 "requires 2 <= sites" 0)
check_cli(1 "nonnegative" -4)
check_cli(1 "nonnegative" 4junk)
check_cli(1 "nonnegative" 999999999999999999999999999999)
check_cli(1 "nonnegative" 4 --max-iterations -1)
check_cli(1 "not expected" 4 --unknown)
check_cli(1 "missing" 4 --precision)
check_cli(1 "not in {fp64,long-double,fp128}" 4 --precision arbitrary)
check_cli(1 "finite and positive" 4 --tolerance 0)
check_cli(1 "finite and positive" 4 --tolerance -1)
check_cli(1 "finite and positive" 4 --tolerance nan)
check_cli(1 "finite and positive" 4 --tolerance inf)
check_cli(1 "invalid real value" 4 --tolerance 1e-10junk)
check_cli(0 "Sz: -0.5" 5 --sz -1/2)
check_cli(0 "Spin-reversed reference: 1" 5 --sz -0.5)
check_cli(0 "Total energy: 1" 4 --sz 2 --max-iterations 0)
check_cli(0 "# Sz momentum_index P energy" 6 --sectors)
check_cli(0 "# hole k momentum_index P energy E_minus_N_e_inf epsilon_inf" 7 --spinons)
check_cli(0 "Sz: 1" 4 --quantum-numbers 0)
check_cli(0 "Sz: 0" 4 --quantum-numbers -1/2,1/2 --roots)
check_cli(0 "Momentum index: 0" 5 --quantum-numbers -1,1)
check_cli(2 "unconverged estimate" 7 --spinons --max-iterations 0)
check_cli(2 "unconverged estimate" 5 --sectors --max-iterations 1)
check_cli(1 "same half-integer parity" 5 --sz 0)
check_cli(1 "Sz must lie" 4 --sz 3)
check_cli(1 "parse failed" 5 --sz 0.25)
check_cli(1 "mutually exclusive" 5 --sz 1/2 --spinons)
check_cli(1 "mutually exclusive" 5 --sectors --quantum-numbers 0)
check_cli(1 "odd N" 6 --spinons)
check_cli(1 "wrong parity" 4 --quantum-numbers -1,1)
check_cli(1 "strictly increasing" 4 --quantum-numbers 1/2,-1/2)
check_cli(1 "parse failed" 4 --quantum-numbers 0,)
check_cli(1 "missing" 4 --sz)
if(FLOAT128)
  # The analytic N=6 energy is -(2+sqrt(13))/2. Require digits far beyond
  # double or x87 precision from the actual executable, not just the library.
  check_cli(0 "Total energy: -2.8027756377319946465596106337" 6 --precision fp128)
  check_cli(0 "Total energy: -0.559016994374947424102293417" 5 --sz 3/2 --precision fp128)
  check_cli(0 "1.570796326794896619231321691" 5 --spinons --precision fp128)
else()
  check_cli(1 "fp128 is unavailable" 6 --precision fp128)
endif()
